"use client";

import React, { useState } from "react";
import { Page, Text, View, Document, StyleSheet, pdf } from "@react-pdf/renderer";

interface ProposalData {
  clientName: string;
  clientCompany: string;
  executiveSummary: string;
  problemStatement: string;
  proposedSolution: string;
  timeline: string;
  investment: string;
  nextSteps: string;
}

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
    paddingBottom: 20,
    borderBottom: "2px solid #1a1a1a",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: "#666",
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 8,
    backgroundColor: "#f5f5f5",
    padding: "8px 12px",
  },
  sectionContent: {
    fontSize: 10,
    lineHeight: 1.5,
    color: "#333",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    borderTop: "1px solid #e5e5e5",
    paddingTop: 10,
    fontSize: 8,
    color: "#999",
    textAlign: "center",
  },
});

// Create Document Component
const ProposalDocument: React.FC<{ data: ProposalData }> = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Proposal</Text>
        <Text style={styles.subtitle}>
          Prepared for {data.clientName} at {data.clientCompany}
        </Text>
        <Text style={styles.subtitle}>Generated by Sophia AI Factory</Text>
      </View>

      {/* Executive Summary */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.sectionContent}>{data.executiveSummary}</Text>
      </View>

      {/* Problem Statement */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Current Challenges</Text>
        <Text style={styles.sectionContent}>{data.problemStatement}</Text>
      </View>

      {/* Proposed Solution */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Proposed Solution</Text>
        <Text style={styles.sectionContent}>{data.proposedSolution}</Text>
      </View>

      {/* Timeline */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Timeline</Text>
        <Text style={styles.sectionContent}>{data.timeline}</Text>
      </View>

      {/* Investment */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Investment</Text>
        <Text style={styles.sectionContent}>{data.investment}</Text>
      </View>

      {/* Next Steps */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Next Steps</Text>
        <Text style={styles.sectionContent}>{data.nextSteps}</Text>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by Sophia AI Factory • Confidential and Proprietary
      </Text>
    </Page>
  </Document>
);

interface PDFExportButtonProps {
  proposalData: ProposalData;
  filename?: string;
}

export async function exportProposalToPDF(
  proposalData: ProposalData,
  filename: string = "proposal.pdf"
): Promise<Blob> {
  const blob = await pdf(<ProposalDocument data={proposalData} />).toBlob();
  return blob;
}

export default function PDFExportButton({ proposalData, filename = "proposal.pdf" }: PDFExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const blob = await exportProposalToPDF(proposalData, filename);
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = filename;
      link.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("PDF export failed:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={isExporting}
      className="inline-flex items-center px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary-hover disabled:opacity-50 disabled:cursor-not-allowed"
    >
      <span className="material-symbols-outlined mr-2">
        {isExporting ? "progress_activity" : "picture_as_pdf"}
      </span>
      {isExporting ? "Exporting..." : "Export PDF"}
    </button>
  );
}
