/**
 * Telegram Executive BI Digest Dispatcher & Formatter
 *
 * Implements:
 * - Telegram MarkdownV2 character escaping for all 18 reserved characters.
 * - Safe 4096-character message chunking without breaking escape sequences or entities.
 * - Key Performance Indicators digest formatting (MRR, throughput, viral score, ROI).
 * - Circuit breaker tracking and plain-text fallback on parse errors.
 *
 * Layer: forest (side-effect dispatcher)
 * Allowed imports: @/seed/*, @/tree/*, @/forest/*
 *
 * @module forest/bi/telegram-digest-sender
 */

import { shouldAllowRequest, recordSuccess, recordFailure } from '@/seed/security/circuit-breaker';
import { classifyError } from '@/seed/types/failure-kind';
import { getErrorMessage } from '@/seed/utils/to-error';
import { logger } from '@/seed/utils/logger-utility';
import type { ExecutiveBIMetricsSummary } from '@/seed/types/executive-bi';
import type { BrandingSettings } from '@/seed/tenant-settings/defaults';

export const TELEGRAM_MAX_MESSAGE_LENGTH = 4096;
export const TELEGRAM_SAFE_CHUNK_LENGTH = 4000;

/** Regex matching all Telegram MarkdownV2 reserved characters requiring a preceding backslash. */
export const TELEGRAM_MARKDOWN_V2_SPECIALS = /([_*[\]()~`>#+\-=|{}.!\\])/g;

/**
 * Strictly escapes all Telegram MarkdownV2 reserved characters with a leading backslash.
 * Characters: _ * [ ] ( ) ~ ` > # + - = | { } . ! \
 */
export function escapeTelegramMarkdownV2(text: string): string {
  return text.replace(TELEGRAM_MARKDOWN_V2_SPECIALS, '\\$1');
}

/**
 * Formats the Executive BI Metrics summary into Telegram MarkdownV2 format.
 * Matches exact contracts in enterprise-test-harness.ts and executive-bi.e2e.test.ts (F2).
 */
export function formatTelegramDigest(
  metrics: ExecutiveBIMetricsSummary,
  branding?: Partial<BrandingSettings> | null,
): string {
  const agency = branding?.agencyName ?? 'Sophia AI Factory';
  const mrrUsd = (metrics.mrrCents / 100).toFixed(2);
  const affiliateUsd = (metrics.affiliateRevenueCents / 100).toFixed(2);
  const spendUsd = (metrics.marketingSpendCents / 100).toFixed(2);

  const raw = `📊 *Executive BI Digest — ${agency}*
• *MRR*: $${mrrUsd}
• *Video Throughput*: ${metrics.throughputCount} videos
• *Viral Score*: ${metrics.viralScore}/100
• *Affiliate Revenue*: $${affiliateUsd}
• *Marketing Spend*: $${spendUsd}
• *ROI*: ${metrics.roiRatio}x

_Automated report generated by Sophia Enterprise Engine_`;

  return escapeTelegramMarkdownV2(raw);
}

/**
 * Splits an already-escaped or formatted MarkdownV2 string into chunks conforming to Telegram limits.
 * Guarantees that:
 * 1. No chunk exceeds maxLength (default 4096).
 * 2. Cuts prefer natural boundaries: paragraph (\n\n) -> newline (\n) -> space ( ).
 * 3. Never splits between a backslash and the escaped character (odd trailing backslash guard).
 * 4. Never splits inside a UTF-16 surrogate pair (emoji guard).
 */
export function splitTelegramMarkdownV2(
  text: string,
  maxLength: number = TELEGRAM_MAX_MESSAGE_LENGTH,
): string[] {
  if (text.length <= maxLength) {
    return [text];
  }

  const chunks: string[] = [];
  let remaining = text;

  while (remaining.length > 0) {
    if (remaining.length <= maxLength) {
      chunks.push(remaining);
      break;
    }

    let cutIndex = maxLength;
    const window = remaining.slice(0, maxLength);

    // 1. Prefer natural boundaries: paragraph -> newline -> space
    const doubleNewline = window.lastIndexOf('\n\n');
    const singleNewline = window.lastIndexOf('\n');
    const space = window.lastIndexOf(' ');

    if (doubleNewline >= maxLength * 0.3) {
      cutIndex = doubleNewline + 2;
    } else if (singleNewline >= maxLength * 0.3) {
      cutIndex = singleNewline + 1;
    } else if (space >= maxLength * 0.3) {
      cutIndex = space + 1;
    }

    // 2. Guard against surrogate pair splitting (high surrogate code unit)
    if (cutIndex > 0) {
      const prevCode = remaining.charCodeAt(cutIndex - 1);
      if (prevCode >= 0xd800 && prevCode <= 0xdbff) {
        cutIndex -= 1;
      }
    }

    // 3. Guard against severed escape sequences (odd trailing backslashes)
    let backslashCount = 0;
    for (let i = cutIndex - 1; i >= 0 && remaining[i] === '\\'; i--) {
      backslashCount++;
    }
    if (backslashCount % 2 === 1) {
      cutIndex -= 1;
    }

    const currentChunk = remaining.slice(0, cutIndex).trimEnd();
    if (currentChunk.length > 0) {
      chunks.push(currentChunk);
    }
    remaining = remaining.slice(cutIndex).trimStart();
  }

  return chunks;
}

export interface TelegramConfig {
  chatId?: string;
  botToken?: string;
  disableWebPagePreview?: boolean;
}

export interface TelegramDigestOptions extends TelegramConfig {
  branding?: Partial<BrandingSettings> | null;
  maxLength?: number;
}

export interface TelegramDigestResult {
  success: boolean;
  totalChunks: number;
  chunksSent: number;
  messageIds: number[];
  error?: string;
  skipped?: boolean;
  reason?: string;
}

/**
 * Sends an Executive BI Digest to Telegram Bot API.
 * Named sendTelegramExecutiveDigest per prompt contract, with sendTelegramDigest as alias.
 */
export async function sendTelegramExecutiveDigest(
  telegramConfig: TelegramConfig,
  metrics: ExecutiveBIMetricsSummary,
  branding?: Partial<BrandingSettings> | null,
): Promise<TelegramDigestResult> {
  const botToken = telegramConfig?.botToken ?? process.env.TELEGRAM_BOT_TOKEN;
  const chatId = telegramConfig?.chatId ?? process.env.TELEGRAM_CHAT_ID;

  if (!botToken || !chatId) {
    logger.warn('[telegram-digest-sender] TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not configured — skipping');
    return {
      success: false,
      skipped: true,
      reason: 'missing_credentials',
      totalChunks: 0,
      chunksSent: 0,
      messageIds: [],
    };
  }

  if (!shouldAllowRequest('telegram')) {
    logger.warn('[telegram-digest-sender] Circuit breaker open for telegram — skipping');
    return {
      success: false,
      skipped: true,
      reason: 'circuit_breaker_open',
      totalChunks: 0,
      chunksSent: 0,
      messageIds: [],
    };
  }

  const formattedText = formatTelegramDigest(metrics, branding);
  const chunks = splitTelegramMarkdownV2(formattedText, TELEGRAM_SAFE_CHUNK_LENGTH);
  const messageIds: number[] = [];

  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];

    try {
      let res = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: chatId,
          text: chunk,
          parse_mode: 'MarkdownV2',
          disable_web_page_preview: telegramConfig?.disableWebPagePreview ?? true,
        }),
        signal: AbortSignal.timeout(10_000),
      });

      // Fallback to plain text on MarkdownV2 parse failure (HTTP 400 with "can't parse")
      if (!res.ok && res.status === 400) {
        const bodyText = await res.text().catch(() => '');
        if (bodyText.includes("can't parse") || bodyText.includes('entities')) {
          logger.warn('[telegram-digest-sender] MarkdownV2 parse failed, falling back to plain text', {
            chatId,
            chunkIndex: i,
          });
          res = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              chat_id: chatId,
              text: chunk.replace(/\\([_*[\]()~`>#+\-=|{}.!\\])/g, '$1'),
              disable_web_page_preview: true,
            }),
            signal: AbortSignal.timeout(10_000),
          });
        }
      }

      if (!res.ok) {
        const errBody = await res.text().catch(() => '');
        recordFailure('telegram', classifyError(new Error(`HTTP ${res.status}`)));
        return {
          success: false,
          totalChunks: chunks.length,
          chunksSent: messageIds.length,
          messageIds,
          error: `Telegram API ${res.status}: ${errBody.slice(0, 200)}`,
        };
      }

      const data = (await res.json()) as { ok: boolean; result?: { message_id: number } };
      if (data.ok && data.result?.message_id) {
        messageIds.push(data.result.message_id);
      }

      // Safe pacing between chunks to respect Telegram rate limits
      if (i < chunks.length - 1) {
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
    } catch (err) {
      recordFailure('telegram', classifyError(err));
      return {
        success: false,
        totalChunks: chunks.length,
        chunksSent: messageIds.length,
        messageIds,
        error: getErrorMessage(err),
      };
    }
  }

  recordSuccess('telegram');
  return {
    success: true,
    totalChunks: chunks.length,
    chunksSent: messageIds.length,
    messageIds,
  };
}

/**
 * Convenient alias matching sendTelegramDigest(metrics, options).
 */
export async function sendTelegramDigest(
  metrics: ExecutiveBIMetricsSummary,
  options: TelegramDigestOptions = {},
): Promise<TelegramDigestResult> {
  return sendTelegramExecutiveDigest(
    {
      chatId: options.chatId,
      botToken: options.botToken,
      disableWebPagePreview: options.disableWebPagePreview,
    },
    metrics,
    options.branding,
  );
}
