/**
 * Audit Report Generator
 * Generates a downloadable Markdown report from an audit run.
 *
 * @module lib/audit/report-generator
 */

import type { AuditRunSummary, CheckResult } from './zero-gap-types'
import { getTrafficLight } from './audit-score-calculator'

function statusIcon(status: string): string {
  if (status === 'pass') return '✅'
  if (status === 'warn') return '⚠️'
  return '❌'
}

function trafficIcon(score: number): string {
  const light = getTrafficLight(score)
  if (light === 'green') return '🟢 GREEN'
  if (light === 'yellow') return '🟡 YELLOW'
  return '🔴 RED'
}

function groupByCategory(results: CheckResult[]): Record<string, CheckResult[]> {
  return results.reduce<Record<string, CheckResult[]>>((acc, r) => {
    const cat = r.category ?? r.id
    if (!acc[cat]) acc[cat] = []
    acc[cat].push(r)
    return acc
  }, {})
}

function getTopFixes(results: CheckResult[]): string[] {
  return results
    .filter((r) => r.status !== 'pass' && r.fix)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 5)
    .map((r) => r.fix!)
}

export function generateMarkdownReport(run: AuditRunSummary): string {
  const date = new Date(run.startedAt * 1000).toISOString()
  const verdict = trafficIcon(run.totalScore)
  const grouped = groupByCategory(run.results)
  const topFixes = getTopFixes(run.results)
  const durationSec = run.completedAt
    ? Math.round((run.completedAt - run.startedAt))
    : '?'

  const lines: string[] = [
    `# Zero-GAP Platform Audit`,
    ``,
    `**Audit ID**: \`${run.id}\`  `,
    `**Date**: ${date}  `,
    `**Duration**: ${durationSec}s  `,
    `**Triggered by**: \`${run.triggeredByUserId}\`  `,
    ``,
    `---`,
    ``,
    `## Score: ${run.totalScore}/100 — ${verdict}`,
    ``,
    `| Metric | Count |`,
    `|--------|-------|`,
    `| ✅ Passed | ${run.passed} |`,
    `| ⚠️ Warnings | ${run.warned} |`,
    `| ❌ Failed | ${run.failed} |`,
    `| Total Checks | ${run.totalChecks} |`,
    ``,
    `---`,
    ``,
  ]

  if (topFixes.length > 0) {
    lines.push(`## Top Priority Fixes`)
    lines.push(``)
    for (const fix of topFixes) {
      lines.push(`- ${fix}`)
    }
    lines.push(``)
    lines.push(`---`)
    lines.push(``)
  }

  lines.push(`## Per-Category Breakdown`)
  lines.push(``)

  for (const [category, checks] of Object.entries(grouped)) {
    lines.push(`### ${category}`)
    lines.push(``)
    lines.push(`| Check | Status | Score | Evidence |`)
    lines.push(`|-------|--------|-------|----------|`)
    for (const c of checks) {
      const icon = statusIcon(c.status)
      const score = `${Math.round(c.score * c.weight)}/${c.weight}`
      const evidence = c.evidence.replace(/\|/g, '\\|').slice(0, 120)
      lines.push(`| ${c.name} | ${icon} ${c.status} | ${score} | ${evidence} |`)
    }
    lines.push(``)

    const failedChecks = checks.filter((c) => c.status !== 'pass' && c.fix)
    if (failedChecks.length > 0) {
      for (const c of failedChecks) {
        lines.push(`> **Fix**: ${c.fix}`)
      }
      lines.push(``)
    }
  }

  lines.push(`---`)
  lines.push(``)
  lines.push(`## Raw Results`)
  lines.push(``)
  lines.push(`\`\`\`json`)
  lines.push(JSON.stringify(run.results, null, 2))
  lines.push(`\`\`\``)
  lines.push(``)
  lines.push(`---`)
  lines.push(`*Generated by Sophia Zero-GAP Audit System*`)

  return lines.join('\n')
}
