import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Head>
        <title>Mekong AgencyOS - Lean Revenue</title>
        <meta name="description" content="Generated by Mekong CLI" />
      </Head>

      <main className="max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl">
            Mekong AgencyOS
          </h1>
          <p className="mt-5 max-w-xl mx-auto text-xl text-gray-500">
            The lean revenue architecture for high-performance agencies.
          </p>
          <div className="mt-8 flex justify-center">
            <Link href="/checkout" className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
              Get Started
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}
