-- SOP Official Seed Data (auto-generated by scripts/generate-sop-seed-sql.mjs)
-- DO NOT EDIT MANUALLY — regenerate with: npm run db:gen-sop-seed
-- Generated at: 2026-05-03T04:41:44.688Z

INSERT OR IGNORE INTO sop_templates (id, slug, name_vi, name_en, description_vi, description_en, category, agents_yaml, playbook_md, output_schema, credits_per_run, version, is_official, author_user_id, status, created_at, updated_at) VALUES ('sop_official_daily_content_factory', 'daily-content-factory', 'Nhà Máy Nội Dung Hàng Ngày', 'Daily Content Factory', 'Tự động tạo 3 video AI và gửi email digest hàng ngày cho khách hàng', 'Auto-generate 3 AI avatar videos and send a daily email digest to customers', 'content', 'agents:
  content_planner:
    role: Content Planner
    goal: Plan 3 daily content topics
    tools:
      - analytics:report
  video_creator:
    role: Video Creator
    goal: Create AI avatar videos
    tools:
      - video:create
  email_publisher:
    role: Email Publisher
    goal: Send daily digest
    tools:
      - email:campaign', '# Daily Content Factory Playbook

## Step 1: analytics:report
```yaml
type: topics
limit: 3
```

## Step 2: video:create
```yaml
topic: "{{step_1.output.topics[0]}}"
```

## Step 3: video:create
```yaml
topic: "{{step_1.output.topics[1]}}"
```

## Step 4: video:create
```yaml
topic: "{{step_1.output.topics[2]}}"
```

## Step 5: email:campaign
```yaml
subject: "Your Daily Video Digest"
template: daily_digest
```', '{"type":"object","required":["videos","emailId"],"properties":{"videos":{"type":"array","items":{"type":"object"},"minItems":3},"emailId":{"type":"string"}}}', 10, 1, 1, NULL, 'published', 1777783304, 1777783304);

INSERT OR IGNORE INTO sop_templates (id, slug, name_vi, name_en, description_vi, description_en, category, agents_yaml, playbook_md, output_schema, credits_per_run, version, is_official, author_user_id, status, created_at, updated_at) VALUES ('sop_official_reactive_lead_engine', 'reactive-lead-engine', 'Động Cơ Lead Phản Ứng', 'Reactive Lead Engine', 'Nhận webhook, làm giàu dữ liệu lead và gửi email cá nhân hóa tự động', 'Receive webhook, enrich lead data, and send a personalized email automatically', 'leads', 'agents:
  lead_enricher:
    role: Lead Enricher
    goal: Enrich lead data
    tools:
      - lead:enrich
  email_writer:
    role: Email Writer
    goal: Send personalized email
    tools:
      - email:test', '# Reactive Lead Engine Playbook

## Step 1: lead:enrich
```yaml
email: "{{trigger.body.email}}"
```

## Step 2: email:test
```yaml
to: "{{step_1.output.email}}"
subject: "Quick question"
```', '{"type":"object","required":["leadId","enriched","emailId"],"properties":{"leadId":{"type":"string"},"enriched":{"type":"object"},"emailId":{"type":"string"}}}', 2, 1, 1, NULL, 'published', 1777783304, 1777783304);

INSERT OR IGNORE INTO sop_templates (id, slug, name_vi, name_en, description_vi, description_en, category, agents_yaml, playbook_md, output_schema, credits_per_run, version, is_official, author_user_id, status, created_at, updated_at) VALUES ('sop_official_weekly_performance_report', 'weekly-performance-report', 'Báo Cáo Hiệu Suất Hàng Tuần', 'Weekly Performance Report', 'Tự động truy vấn analytics, tạo báo cáo và gửi email hàng tuần', 'Auto-query analytics, generate performance report, and email weekly summary', 'analytics', 'agents:
  analytics_reporter:
    role: Analytics Reporter
    goal: Generate weekly metrics
    tools:
      - analytics:report
  report_sender:
    role: Report Sender
    goal: Email the report
    tools:
      - email:campaign', '# Weekly Performance Report Playbook

## Step 1: analytics:report
```yaml
period: last_7_days
```

## Step 2: email:campaign
```yaml
subject: "Weekly Performance Report"
template: weekly_report
```', '{"type":"object","required":["reportId","emailId","metricsSnapshot"],"properties":{"reportId":{"type":"string"},"emailId":{"type":"string"},"metricsSnapshot":{"type":"object"}}}', 1, 1, 1, NULL, 'published', 1777783304, 1777783304);

INSERT OR IGNORE INTO sop_templates (id, slug, name_vi, name_en, description_vi, description_en, category, agents_yaml, playbook_md, output_schema, credits_per_run, version, is_official, author_user_id, status, created_at, updated_at) VALUES ('sop_official_proposal_auto_pilot', 'proposal-auto-pilot', 'Tự Động Gửi Đề Xuất', 'Proposal Auto-Pilot', 'Hàng ngày tìm 5 lead, tạo đề xuất cá nhân hóa và gửi cho từng người', 'Daily: find 5 prospects, create personalized proposals, and send to each one', 'proposals', 'agents:
  lead_finder:
    role: Lead Finder
    goal: Find 5 prospects
    tools:
      - lead:find
  proposal_creator:
    role: Proposal Creator
    goal: Create proposals
    tools:
      - proposal:create
  proposal_sender:
    role: Proposal Sender
    goal: Send proposals
    tools:
      - email:campaign', '# Proposal Auto-Pilot Playbook

## Step 1: lead:find
```yaml
limit: 5
```

## Step 2: proposal:create
```yaml
leads: "{{step_1.output.leads}}"
```

## Step 3: email:campaign
```yaml
proposals: "{{step_2.output.proposals}}"
```', '{"type":"object","required":["proposals"],"properties":{"proposals":{"type":"array","items":{"type":"object","properties":{"proposalId":{"type":"string"},"leadId":{"type":"string"}},"required":["proposalId","leadId"]},"minItems":1}}}', 5, 1, 1, NULL, 'published', 1777783304, 1777783304);

INSERT OR IGNORE INTO sop_templates (id, slug, name_vi, name_en, description_vi, description_en, category, agents_yaml, playbook_md, output_schema, credits_per_run, version, is_official, author_user_id, status, created_at, updated_at) VALUES ('sop_official_crisis_pr_mode', 'crisis-pr-mode', 'Chế Độ Khủng Hoảng PR', 'Crisis PR Mode', 'Theo dõi đề cập thương hiệu, soạn thảo phản hồi — yêu cầu phê duyệt người trước khi gửi', 'Monitor brand mentions, draft crisis response — requires human approval before sending', 'crisis', 'agents:
  mention_monitor:
    role: Mention Monitor
    goal: Detect negative mentions
    tools:
      - analytics:report
  response_drafter:
    role: Response Drafter
    goal: Draft crisis response
    tools:
      - proposal:create', '# Crisis PR Mode Playbook

## Step 1: analytics:report
```yaml
type: mentions
sentiment: negative
```

## Step 2: proposal:create
```yaml
type: crisis_response
requires_approval: true
```', '{"type":"object","required":["mentionsReport","draftResponseId","requiresApproval"],"properties":{"mentionsReport":{"type":"object"},"draftResponseId":{"type":"string"},"requiresApproval":{"type":"boolean","const":true}}}', 3, 1, 1, NULL, 'published', 1777783304, 1777783304);
