/**
 * Outcome-Based Pricing Types
 *
 * Supports the platform's RaaS billing model where fees are calculated as a
 * percentage of gross revenue generated by an execution outcome.
 */

export type PricingModel = 'fixed_subscription' | 'outcome_percentage' | 'hybrid'

export type BillingStatus = 'pending' | 'invoiced' | 'settled' | 'disputed' | 'waived'

/**
 * A pricing tier that maps revenue ranges to fee percentages.
 * Allows volume discounts: higher gross revenue → lower percentage.
 */
export interface OutcomePricingTier {
  id: string
  name: string
  /** Fee as a percentage of gross revenue (e.g. 15.0 = 15%) */
  percentage: number
  /** Minimum gross revenue in cents for this tier to apply */
  minRevenueCents: number
  /** Maximum gross revenue in cents (inclusive). Null = no upper bound. */
  maxRevenueCents?: number
  isActive: boolean
  createdAt: number
  updatedAt: number
}

/**
 * A single billable event recording the fee charged for one execution outcome.
 */
export interface BillingEvent {
  id: string
  userId: string
  executionId: string
  /** Optional: links back to a sop_execution_outcomes row */
  outcomeId?: string
  grossRevenueCents: number
  feeCents: number
  feePercentage: number
  pricingTierId?: string
  status: BillingStatus
  /** Unix epoch seconds; set when status → 'settled' */
  settledAt?: number
  createdAt: number
}

/**
 * Aggregated billing summary for a creator over a time period.
 */
export interface CreatorBillingSummary {
  userId: string
  totalGrossRevenueCents: number
  totalFeesCents: number
  totalSettledCents: number
  pendingFeesCents: number
  /** ISO date string or 'all-time' */
  period: string
}
