/**
 * Seed data: top SaaS affiliate programs
 *
 * 30+ programs seeded manually as bootstrap data.
 * commission_rate is percentage (e.g., 30 = 30%).
 */

import type { RawProgram } from '@/types/affiliate';

export const SEED_PROGRAMS: RawProgram[] = [
  {
    name: 'HeyGen',
    company: 'HeyGen Inc.',
    url: 'https://www.heygen.com',
    signup_url: 'https://www.heygen.com/affiliate',
    commission_rate: 30,
    commission_type: 'recurring',
    cookie_duration_days: 60,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'AI video generation platform — talking-head videos from text.',
    source: 'manual',
  },
  {
    name: 'HubSpot',
    company: 'HubSpot Inc.',
    url: 'https://www.hubspot.com',
    signup_url: 'https://www.hubspot.com/partners/affiliates',
    commission_rate: 30,
    commission_type: 'recurring',
    cookie_duration_days: 180,
    payout_threshold: 10,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'CRM, marketing, sales, and service software.',
    source: 'manual',
  },
  {
    name: 'Notion',
    company: 'Notion Labs Inc.',
    url: 'https://www.notion.so',
    signup_url: 'https://affiliate.notion.so',
    commission_rate: 50,
    commission_type: 'one-time',
    cookie_duration_days: 90,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'All-in-one workspace for notes, docs, and wikis.',
    source: 'manual',
  },
  {
    name: 'Canva',
    company: 'Canva Pty Ltd',
    url: 'https://www.canva.com',
    signup_url: 'https://www.canva.com/affiliates',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'design',
    description: 'Online graphic design tool for presentations and social media.',
    source: 'manual',
  },
  {
    name: 'Shopify',
    company: 'Shopify Inc.',
    url: 'https://www.shopify.com',
    signup_url: 'https://www.shopify.com/affiliates',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 25,
    payout_frequency: 'monthly',
    niche: 'ecommerce',
    description: 'E-commerce platform for online stores.',
    source: 'manual',
  },
  {
    name: 'ConvertKit',
    company: 'ConvertKit LLC',
    url: 'https://convertkit.com',
    signup_url: 'https://convertkit.com/affiliate',
    commission_rate: 30,
    commission_type: 'recurring',
    cookie_duration_days: 60,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'Email marketing platform for creators.',
    source: 'manual',
  },
  {
    name: 'Semrush',
    company: 'Semrush Inc.',
    url: 'https://www.semrush.com',
    signup_url: 'https://www.semrush.com/lp/brand-monitoring-affiliate',
    commission_rate: 40,
    commission_type: 'recurring',
    cookie_duration_days: 120,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'SEO, PPC, content, social media, and competitive research tools.',
    source: 'manual',
  },
  {
    name: 'ActiveCampaign',
    company: 'ActiveCampaign LLC',
    url: 'https://www.activecampaign.com',
    signup_url: 'https://www.activecampaign.com/partner/affiliate',
    commission_rate: 25,
    commission_type: 'recurring',
    cookie_duration_days: 90,
    payout_threshold: 100,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'Email marketing, marketing automation, and CRM.',
    source: 'manual',
  },
  {
    name: 'ClickFunnels',
    company: 'Etison LLC',
    url: 'https://www.clickfunnels.com',
    signup_url: 'https://www.clickfunnels.com/affiliates',
    commission_rate: 30,
    commission_type: 'recurring',
    cookie_duration_days: 45,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'Sales funnel builder for online businesses.',
    source: 'manual',
  },
  {
    name: 'Jasper AI',
    company: 'Jasper AI Inc.',
    url: 'https://www.jasper.ai',
    signup_url: 'https://www.jasper.ai/affiliate-program',
    commission_rate: 30,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 25,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'AI writing assistant for marketing teams.',
    source: 'manual',
  },
  {
    name: 'Surfer SEO',
    company: 'Surfer SEO',
    url: 'https://surferseo.com',
    signup_url: 'https://surferseo.com/affiliate',
    commission_rate: 25,
    commission_type: 'recurring',
    cookie_duration_days: 60,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'SEO content optimization and planning tool.',
    source: 'manual',
  },
  {
    name: 'Monday.com',
    company: 'monday.com Ltd',
    url: 'https://monday.com',
    signup_url: 'https://monday.com/affiliates',
    commission_rate: 30,
    commission_type: 'one-time',
    cookie_duration_days: 90,
    payout_threshold: 100,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'Work OS for project management and team collaboration.',
    source: 'manual',
  },
  {
    name: 'Grammarly',
    company: 'Grammarly Inc.',
    url: 'https://www.grammarly.com',
    signup_url: 'https://www.grammarly.com/affiliates',
    commission_rate: 20,
    commission_type: 'one-time',
    cookie_duration_days: 90,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'AI writing assistant for grammar and clarity.',
    source: 'manual',
  },
  {
    name: 'NordVPN',
    company: 'Nord Security',
    url: 'https://nordvpn.com',
    signup_url: 'https://nordvpn.com/affiliates',
    commission_rate: 40,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 10,
    payout_frequency: 'monthly',
    niche: 'security',
    description: 'VPN service for privacy and security.',
    source: 'manual',
  },
  {
    name: 'Leadpages',
    company: 'Leadpages Inc.',
    url: 'https://www.leadpages.com',
    signup_url: 'https://www.leadpages.com/affiliate-program',
    commission_rate: 50,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'Landing page builder for lead generation.',
    source: 'manual',
  },
  {
    name: 'Apollo.io',
    company: 'Apollo.io Inc.',
    url: 'https://www.apollo.io',
    signup_url: 'https://www.apollo.io/affiliate',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'Sales intelligence and engagement platform.',
    source: 'manual',
  },
  {
    name: 'Freshworks',
    company: 'Freshworks Inc.',
    url: 'https://www.freshworks.com',
    signup_url: 'https://www.freshworks.com/partners/affiliate',
    commission_rate: 15,
    commission_type: 'one-time',
    cookie_duration_days: 90,
    payout_threshold: 100,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'Customer service, CRM, and IT management software.',
    source: 'manual',
  },
  {
    name: 'Ahrefs',
    company: 'Ahrefs Pte. Ltd.',
    url: 'https://ahrefs.com',
    signup_url: 'https://ahrefs.com/affiliate-program',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 60,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'SEO tools for backlinks, keywords, and site audits.',
    source: 'manual',
  },
  {
    name: 'Webflow',
    company: 'Webflow Inc.',
    url: 'https://webflow.com',
    signup_url: 'https://webflow.com/affiliate',
    commission_rate: 50,
    commission_type: 'recurring',
    cookie_duration_days: 90,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'dev-tools',
    description: 'No-code website builder with CMS and hosting.',
    source: 'manual',
  },
  {
    name: 'Typeform',
    company: 'Typeform SL',
    url: 'https://www.typeform.com',
    signup_url: 'https://www.typeform.com/partners',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'Interactive forms and surveys that people enjoy filling out.',
    source: 'manual',
  },
  {
    name: 'Pipedrive',
    company: 'Pipedrive Inc.',
    url: 'https://www.pipedrive.com',
    signup_url: 'https://www.pipedrive.com/en/partners/affiliates',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 45,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'Sales CRM and pipeline management tool.',
    source: 'manual',
  },
  {
    name: 'Loom',
    company: 'Loom Inc.',
    url: 'https://www.loom.com',
    signup_url: 'https://www.loom.com/affiliates',
    commission_rate: 15,
    commission_type: 'recurring',
    cookie_duration_days: 60,
    payout_threshold: 25,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'Async video messaging for teams.',
    source: 'manual',
  },
  {
    name: 'Figma',
    company: 'Figma Inc.',
    url: 'https://www.figma.com',
    signup_url: 'https://www.figma.com/partners',
    commission_rate: 20,
    commission_type: 'one-time',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'design',
    description: 'Collaborative interface design tool.',
    source: 'manual',
  },
  {
    name: 'Stripe',
    company: 'Stripe Inc.',
    url: 'https://stripe.com',
    signup_url: 'https://stripe.com/partners',
    commission_rate: 15,
    commission_type: 'one-time',
    cookie_duration_days: 30,
    payout_threshold: 25,
    payout_frequency: 'monthly',
    niche: 'finance',
    description: 'Payment infrastructure for internet businesses.',
    source: 'manual',
  },
  {
    name: 'Datadog',
    company: 'Datadog Inc.',
    url: 'https://www.datadoghq.com',
    signup_url: 'https://www.datadoghq.com/partner/program',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 100,
    payout_frequency: 'monthly',
    niche: 'analytics',
    description: 'Cloud monitoring, APM, and security observability.',
    source: 'manual',
  },
  {
    name: 'Intercom',
    company: 'Intercom Inc.',
    url: 'https://www.intercom.com',
    signup_url: 'https://www.intercom.com/partners',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'saas',
    description: 'Customer messaging platform with live chat and automation.',
    source: 'manual',
  },
  {
    name: 'Zapier',
    company: 'Zapier Inc.',
    url: 'https://zapier.com',
    signup_url: 'https://zapier.com/platform/partner-program',
    commission_rate: 25,
    commission_type: 'recurring',
    cookie_duration_days: 90,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'No-code automation connecting 5,000+ apps.',
    source: 'manual',
  },
  {
    name: 'ClickUp',
    company: 'Mango Technologies Inc.',
    url: 'https://clickup.com',
    signup_url: 'https://clickup.com/affiliates',
    commission_rate: 20,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'All-in-one project management and productivity platform.',
    source: 'manual',
  },
  {
    name: 'Slack',
    company: 'Salesforce Inc.',
    url: 'https://slack.com',
    signup_url: 'https://slack.com/partners',
    commission_rate: 10,
    commission_type: 'one-time',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'productivity',
    description: 'Team messaging and collaboration platform.',
    source: 'manual',
  },
  {
    name: 'Mailchimp',
    company: 'The Rocket Science Group LLC',
    url: 'https://mailchimp.com',
    signup_url: 'https://mailchimp.com/about/partner',
    commission_rate: 30,
    commission_type: 'recurring',
    cookie_duration_days: 30,
    payout_threshold: 50,
    payout_frequency: 'monthly',
    niche: 'marketing',
    description: 'Email marketing and automation for growing businesses.',
    source: 'manual',
  },
  {
    name: 'Bubble',
    company: 'Bubble Group Inc.',
    url: 'https://bubble.io',
    signup_url: 'https://bubble.io/partners',
    commission_rate: 25,
    commission_type: 'recurring',
    cookie_duration_days: 60,
    payout_threshold: 25,
    payout_frequency: 'monthly',
    niche: 'dev-tools',
    description: 'No-code app development platform.',
    source: 'manual',
  },
];
