-- Onboarding automation tables
-- Part of Track D: Customer onboarding automation

-- Milestone tracking: records each step of the 14-day onboarding SOP
CREATE TABLE IF NOT EXISTS onboarding_progress (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  milestone TEXT NOT NULL,
  achieved_at TEXT NOT NULL DEFAULT (datetime('now')),
  achieved_by TEXT NOT NULL,
  notes TEXT,
  UNIQUE(tenant_id, milestone)
);

CREATE INDEX IF NOT EXISTS idx_onboarding_progress_tenant
  ON onboarding_progress(tenant_id);

-- At-risk alerts: generated by daily cron check
CREATE TABLE IF NOT EXISTS onboarding_alerts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  flags TEXT NOT NULL,  -- comma-separated flag names
  detected_at TEXT NOT NULL DEFAULT (datetime('now')),
  resolved INTEGER NOT NULL DEFAULT 0,
  resolved_at TEXT,
  resolved_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_onboarding_alerts_tenant
  ON onboarding_alerts(tenant_id, resolved);

-- Extend tenants table with onboarding columns (idempotent)
ALTER TABLE tenants ADD COLUMN onboarding_status TEXT DEFAULT 'not_started';
ALTER TABLE tenants ADD COLUMN onboarding_progress_pct INTEGER DEFAULT 0;
ALTER TABLE tenants ADD COLUMN onboarding_paused_reason TEXT;
