/**
 * Environment Variable Sanitizer & Customer Export Generator
 * Layer: tree (Domain operations; imports only from @/seed)
 *
 * Ingests .env.example as canonical schema, masks sensitive secrets
 * with length indicators, preserves public configurations, and flags
 * missing mandatory production keys.
 *
 * @module tree/handover/env-export-generator
 */

import type { SanitizedEnvResult } from '@/seed/handover/handover-types';

/** Set of keys strictly classified as public/non-sensitive */
export const PUBLIC_CONFIG_KEYS = new Set<string>([
  'NEXT_PUBLIC_APP_URL',
  'BETTER_AUTH_URL',
  'NEXT_PUBLIC_DISTRIBUTE_ENABLED',
  'NEXT_PUBLIC_CRISP_WEBSITE_ID',
  'IS_CONFIGURED',
  'FEATURE_PAYOS',
  'QUOTA_FAIL_CLOSED',
  'DISABLE_LLM_CIRCUIT_BREAKER',
  'ENABLE_ORG_QUOTAS',
  'R2_PUBLIC_HOSTNAME',
  'SENTRY_ORG',
  'SENTRY_PROJECT',
  'SENTRY_RELEASE',
  'RESEND_FROM_EMAIL',
  'SUPPORT_EMAIL',
  'FOUNDER_EMAIL',
  'HONEYCOMB_DATASET',
  'OTEL_EXPORTER_OTLP_ENDPOINT',
  'OTEL_SERVICE_NAME',
  'OTEL_SAMPLERATE',
  'INSTAGRAM_REDIRECT_URI',
  'TIKTOK_REDIRECT_URI',
  'YOUTUBE_REDIRECT_URI',
  'ELEVENLABS_VOICE_ID',
  'RUNPOD_ENDPOINT_ID',
]);

/** Set of mandatory production keys that must be defined */
export const MANDATORY_PRODUCTION_KEYS = new Set<string>([
  'BETTER_AUTH_SECRET',
  'BETTER_AUTH_URL',
  'NEXT_PUBLIC_APP_URL',
  'CRON_SECRET',
  'API_ENCRYPTION_KEY',
  'BYOK_MASTER_KEY',
  'NOWPAYMENTS_API_KEY',
  'NOWPAYMENTS_IPN_SECRET',
  'RESEND_API_KEY',
]);

/**
 * Categorizes whether a given key represents a sensitive secret.
 */
export function isSensitiveKey(key: string): boolean {
  if (PUBLIC_CONFIG_KEYS.has(key)) return false;
  const upper = key.toUpperCase();
  return (
    upper.includes('SECRET') ||
    upper.includes('KEY') ||
    upper.includes('TOKEN') ||
    upper.includes('PASSWORD') ||
    upper.includes('AUTH') ||
    upper.includes('CREDENTIAL') ||
    upper.includes('DSN') ||
    upper.includes('SALT')
  );
}

/**
 * Creates a deterministic masked placeholder for a sensitive secret value.
 */
export function maskSecretValue(key: string, value: string | undefined): string {
  const len = value ? value.length : 0;
  const upper = key.toUpperCase();

  if (len === 0) {
    if (upper.includes('KEY')) return '[REDACTED_KEY:len=0]';
    if (upper.includes('TOKEN')) return '[REDACTED_TOKEN:len=0]';
    return '[REDACTED_SECRET:len=0]';
  }

  if (upper.includes('API_ENCRYPTION') || upper.includes('MASTER_KEY')) {
    return `[REDACTED_KEY:len=${len}]`;
  }
  if (upper.includes('API_KEY')) {
    return `[REDACTED_API_KEY:len=${len}]`;
  }
  if (upper.includes('TOKEN')) {
    return `[REDACTED_TOKEN:len=${len}]`;
  }

  return `[REDACTED_SECRET:len=${len}]`;
}

/**
 * Generates a sanitized .env.production bundle based on .env.example template
 * and current runtime environment variables.
 */
export function generateSanitizedEnvProduction(
  envExampleContent: string,
  currentEnv: Record<string, string | undefined> = {},
): SanitizedEnvResult {
  const lines = envExampleContent.split(/\r?\n/);
  const outputLines: string[] = [];
  const missingKeys: string[] = [];
  const warnings: string[] = [];

  let sectionCount = 0;
  let totalKeys = 0;

  outputLines.push('# ==============================================================================');
  outputLines.push('# SOPHIA AI FACTORY — SANITIZED CUSTOMER PRODUCTION ENVIRONMENT EXPORT');
  outputLines.push('# Generated by Phase 20 Automated Customer Handover Engine');
  outputLines.push(`# Exported At: ${new Date().toISOString()}`);
  outputLines.push('# NOTE: All cryptographic secrets and API keys are redacted with length markers.');
  outputLines.push('# ==============================================================================');
  outputLines.push('');

  for (const line of lines) {
    const trimmed = line.trim();

    // Preserve section comment headers
    if (trimmed.startsWith('#') || trimmed === '') {
      if (trimmed.startsWith('# ───') || trimmed.startsWith('# Phase')) {
        sectionCount++;
      }
      outputLines.push(line);
      continue;
    }

    // Process KEY=VALUE lines
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) {
      outputLines.push(line);
      continue;
    }

    const key = line.slice(0, eqIdx).trim();
    const defaultValue = line.slice(eqIdx + 1).trim();
    totalKeys++;

    const runtimeVal = currentEnv[key];
    const isMandatory = MANDATORY_PRODUCTION_KEYS.has(key);
    const isMissing = !runtimeVal && !defaultValue;

    if (isMandatory && isMissing) {
      missingKeys.push(key);
      const warnMsg = `MISSING MANDATORY CONFIGURATION KEY: ${key}`;
      warnings.push(warnMsg);
      outputLines.push(`# ⚠️ WARNING: ${warnMsg}`);
    }

    if (isSensitiveKey(key)) {
      const masked = maskSecretValue(key, runtimeVal || defaultValue);
      outputLines.push(`${key}=${masked}`);
    } else {
      // Public / safe configuration
      const effectiveVal = runtimeVal || defaultValue || '';
      outputLines.push(`${key}=${effectiveVal}`);
    }
  }

  return {
    sanitizedContent: outputLines.join('\n'),
    missingKeys,
    totalKeys,
    sectionCount: Math.max(sectionCount, 1),
    warnings,
  };
}
