/**
 * Regional Advertising & AI Compliance Validation Engine
 *
 * Layer: tree (pure domain logic, algorithms, zero side effects)
 * Supports Milestone $800k MRR:
 * - EU AI Act (Article 50): Mandatory synthetic media disclosures & watermark
 * - US FTC Endorsement Guides: Deceptive AI personas & unsubstantiated claims
 * - Japan 景表法 (景品表示法): Stealth marketing ban (ステマ規制) & 優良誤認/有利誤認
 * - Vietnam Decree 13/2023/NĐ-CP & Luật Quảng cáo: AI synthetic media labels & prohibited claims
 * - Singapore IMDA / PDPA & Global baseline compliance
 *
 * @module tree/cultural-adaptation/compliance-engine
 */

import type {
  ComplianceJurisdiction,
  ComplianceValidationResult,
  ComplianceViolation,
  ComplianceRequiredLabels,
  ContentAuditRecord,
  DisclosurePosition,
  ComplianceStatus,
} from '@/seed/types/cultural-adaptation';

// ─── Canonical Regional Rule Models ──────────────────────────────────────────

interface JurisdictionRuleDef {
  jurisdiction: ComplianceJurisdiction;
  mandatoryLabelEn: string;
  mandatoryLabelLocal: string;
  audioDisclaimerEn: string;
  audioDisclaimerLocal: string;
  defaultPosition: DisclosurePosition;
  watermarkRequired: boolean;
  audioDisclosureRequired: boolean;
  forbiddenRules: Array<{
    ruleId: string;
    category: string;
    regex: RegExp;
    message: string;
    severity: 'warning' | 'error';
    safeReplacement?: string;
  }>;
}

const JURISDICTION_RULES: Record<ComplianceJurisdiction, JurisdictionRuleDef> = {
  EU: {
    jurisdiction: 'EU',
    mandatoryLabelEn: 'AI-Generated Content (Sophia AI)',
    mandatoryLabelLocal: 'Contenu généré par IA (Sophia AI)',
    audioDisclaimerEn: 'This audio features synthetic voices generated by Sophia AI.',
    audioDisclaimerLocal: 'Cet enregistrement audio utilise des voix synthétiques créées par Sophia AI.',
    defaultPosition: 'bottom_right',
    watermarkRequired: true,
    audioDisclosureRequired: true,
    forbiddenRules: [
      {
        ruleId: 'eu-ai-act-art50-guaranteed-return',
        category: 'consumer_protection',
        regex: /\b(100%\s*guaranteed\s*return|zero\s*risk|instant\s*riches|miracle\s*cure)\b/gi,
        message: 'EU AI Act & Consumer Rights Directive prohibit misleading guaranteed financial or health claims.',
        severity: 'error',
        safeReplacement: 'verified methodology',
      },
      {
        ruleId: 'eu-ai-act-unlabeled-deepfake',
        category: 'ai_disclosure',
        regex: /\b(real\s*human\s*spokesperson|not\s*an\s*ai|100%\s*authentic\s*human)\b/gi,
        message: 'EU AI Act Article 50 explicitly prohibits deceiving viewers regarding synthetic identity.',
        severity: 'error',
        safeReplacement: 'Sophia AI virtual presenter',
      },
      {
        ruleId: 'eu-gdpr-biometric-claim',
        category: 'data_privacy',
        regex: /\b(we\s*scan\s*your\s*face|emotion\s*recognition\s*in\s*workplace)\b/gi,
        message: 'EU AI Act prohibits real-time biometric categorization and workplace emotion detection.',
        severity: 'error',
        safeReplacement: 'audience analytics',
      },
    ],
  },
  US: {
    jurisdiction: 'US',
    mandatoryLabelEn: 'Synthetic Media: Created with Sophia AI',
    mandatoryLabelLocal: 'Synthetic Media: Created with Sophia AI',
    audioDisclaimerEn: 'Voice narration produced with Sophia AI.',
    audioDisclaimerLocal: 'Voice narration produced with Sophia AI.',
    defaultPosition: 'bottom_right',
    watermarkRequired: true,
    audioDisclosureRequired: false,
    forbiddenRules: [
      {
        ruleId: 'us-ftc-endorsement-false-doctor',
        category: 'consumer_protection',
        regex: /\b(FDA\s*approved\s*AI|doctor\s*certified\s*miracle|cure-all|guaranteed\s*profit)\b/gi,
        message: 'FTC Endorsement Guides prohibit fabricated regulatory approvals and unsubstantiated health claims.',
        severity: 'error',
        safeReplacement: 'clinically formulated',
      },
      {
        ruleId: 'us-ftc-deceptive-ai-persona',
        category: 'stealth_marketing',
        regex: /\b(i\s*am\s*a\s*real\s*customer|speaking\s*from\s*my\s*personal\s*experience)\b/gi,
        message: 'FTC prohibits synthetic AI avatars claiming bona fide personal product experience without disclosure.',
        severity: 'warning',
        safeReplacement: 'on behalf of satisfied users',
      },
      {
        ruleId: 'us-ftc-risk-free',
        category: 'consumer_protection',
        regex: /\b(risk-free\s*investment|double\s*your\s*money\s*guaranteed)\b/gi,
        message: 'FTC Act Section 5 prohibits deceptive commercial practices regarding guaranteed financial gains.',
        severity: 'error',
        safeReplacement: 'strategic investment potential',
      },
    ],
  },
  JP: {
    jurisdiction: 'JP',
    mandatoryLabelEn: 'Advertisement / AI-Generated (Sophia AI)',
    mandatoryLabelLocal: 'PR / AI生成動画 (Sophia AI)',
    audioDisclaimerEn: 'This video includes AI-generated audio by Sophia AI.',
    audioDisclaimerLocal: '本動画の音声および映像はSophia AIにより生成されています。',
    defaultPosition: 'bottom_right',
    watermarkRequired: true,
    audioDisclosureRequired: true,
    forbiddenRules: [
      {
        ruleId: 'jp-keihyo-stealth-marketing',
        category: 'stealth_marketing',
        regex: /(一般人の感想|個人の体験談(です)?|絶対に儲かる|完全無料(?!（[^）]+）))/gi,
        message: '消費者庁景品表示法（ステマ規制）により、AI広告における誤認表示や誇大表現は禁止されています。',
        severity: 'error',
        safeReplacement: '※個人の感想であり効果を保証するものではありません',
      },
      {
        ruleId: 'jp-keihyo-superior-quality-misleading',
        category: 'consumer_protection',
        regex: /(世界一|国内No\.?1|ナンバーワン|業界最高峰|絶対に効く|効果絶大)/gi,
        message: '客観的調査に基づかない優良誤認（No.1表示等）は景表法第5条第1号に抵触します。',
        severity: 'error',
        safeReplacement: '業界トップクラス水準（当社調べ）',
      },
      {
        ruleId: 'jp-keihyo-advantageous-terms',
        category: 'consumer_protection',
        regex: /(今だけ無料|誰でも確実に稼げる|ノーリスク)/gi,
        message: '有利誤認表示（誰でも確実に稼げる・ノーリスク等）は景表法上違法です。',
        severity: 'error',
        safeReplacement: '期間限定トライアル提供中',
      },
    ],
  },
  VN: {
    jurisdiction: 'VN',
    mandatoryLabelEn: 'Content created with Sophia AI',
    mandatoryLabelLocal: 'Nội dung được tạo bằng trí tuệ nhân tạo (Sophia AI)',
    audioDisclaimerEn: 'Voice commentary synthesized with Sophia AI.',
    audioDisclaimerLocal: 'Giọng đọc và nội dung được tạo tự động bằng trí tuệ nhân tạo Sophia AI.',
    defaultPosition: 'bottom_right',
    watermarkRequired: true,
    audioDisclosureRequired: true,
    forbiddenRules: [
      {
        ruleId: 'vn-decree13-ai-persona-disclosure',
        category: 'ai_disclosure',
        regex: /(người\s*thật\s*100%|không\s*phải\s*ai|bác\s*sĩ\s*trực\s*tiếp\s*khám)/gi,
        message: 'Nghị định 13/2023/NĐ-CP & Luật Quảng cáo cấm giả mạo danh tính cá nhân và chuyên gia y tế bằng AI.',
        severity: 'error',
        safeReplacement: 'Trợ lý AI Sophia đại diện',
      },
      {
        ruleId: 'vn-ad-law-cure-all',
        category: 'consumer_protection',
        regex: /(chữa\s*khỏi\s*100%|cam\s*kết\s*dứt\s*điểm|thuốc\s*tiên|trị\s*dứt\s*bệnh\s*tận\s*gốc)/gi,
        message: 'Luật Quảng cáo 2012 nghiêm cấm quảng cáo dược phẩm / thực phẩm chức năng khẳng định chữa khỏi 100%.',
        severity: 'error',
        safeReplacement: 'hỗ trợ cải thiện hiệu quả',
      },
      {
        ruleId: 'vn-ad-law-unconditional-refund',
        category: 'consumer_protection',
        regex: /(hoàn\s*tiền\s*vô\s*điều\s*kiện|lợi\s*nhuận\s*cam\s*kết\s*100%|lãi\s*suất\s*khủng\s*chắc\s*chắn)/gi,
        message: 'Quy định quản lý quảng cáo tài chính nghiêm cấm hứa hẹn lợi nhuận chắc chắn không rủi ro.',
        severity: 'error',
        safeReplacement: 'tiềm năng sinh lời bền vững',
      },
    ],
  },
  SG: {
    jurisdiction: 'SG',
    mandatoryLabelEn: 'AI Synthesized Media (Sophia AI)',
    mandatoryLabelLocal: 'AI Synthesized Media (Sophia AI)',
    audioDisclaimerEn: 'Synthetic audio generated with Sophia AI.',
    audioDisclaimerLocal: 'Synthetic audio generated with Sophia AI.',
    defaultPosition: 'bottom_right',
    watermarkRequired: true,
    audioDisclosureRequired: false,
    forbiddenRules: [
      {
        ruleId: 'sg-cpex-misleading-claims',
        category: 'consumer_protection',
        regex: /\b(guaranteed\s*financial\s*returns|100%\s*risk-free|instant\s*passive\s*income)\b/gi,
        message: 'Singapore Consumer Protection (Fair Trading) Act prohibits deceptive financial promises.',
        severity: 'error',
        safeReplacement: 'transparent investment approach',
      },
    ],
  },
  GLOBAL: {
    jurisdiction: 'GLOBAL',
    mandatoryLabelEn: 'Created with Sophia AI',
    mandatoryLabelLocal: 'Created with Sophia AI',
    audioDisclaimerEn: 'Audio synthesized by Sophia AI.',
    audioDisclaimerLocal: 'Audio synthesized by Sophia AI.',
    defaultPosition: 'bottom_right',
    watermarkRequired: true,
    audioDisclosureRequired: false,
    forbiddenRules: [
      {
        ruleId: 'global-standard-fraudulent-promise',
        category: 'consumer_protection',
        regex: /\b(100%\s*guaranteed|miracle\s*cure|double\s*your\s*money)\b/gi,
        message: 'Global advertising baseline prohibits fraudulent or unverified performance guarantees.',
        severity: 'warning',
        safeReplacement: 'exceptional performance results',
      },
    ],
  },
};

// ─── Content Scanner & Validator ─────────────────────────────────────────────

export interface ScanContentOptions {
  hasAiVoice?: boolean;
  hasAiAvatar?: boolean;
  customRules?: Array<{
    ruleId: string;
    regex: RegExp;
    message: string;
    severity?: 'warning' | 'error';
  }>;
}

/**
 * Scan video script and content metadata against target regional advertising regulations.
 */
export function scanContentCompliance(
  script: string,
  jurisdiction: ComplianceJurisdiction,
  options?: ScanContentOptions,
): ComplianceValidationResult {
  const ruleDef = JURISDICTION_RULES[jurisdiction] || JURISDICTION_RULES.GLOBAL;
  const violations: ComplianceViolation[] = [];

  // Check forbidden terms in jurisdiction rules
  for (const rule of ruleDef.forbiddenRules) {
    const matches = script.match(rule.regex);
    if (matches && matches.length > 0) {
      for (const m of Array.from(new Set(matches))) {
        violations.push({
          category: rule.category,
          ruleId: rule.ruleId,
          matchedText: m,
          message: rule.message,
          severity: rule.severity,
        });
      }
    }
  }

  // Check any caller-provided custom rules
  if (options?.customRules) {
    for (const rule of options.customRules) {
      const matches = script.match(rule.regex);
      if (matches && matches.length > 0) {
        for (const m of Array.from(new Set(matches))) {
          violations.push({
            category: 'custom_compliance',
            ruleId: rule.ruleId,
            matchedText: m,
            message: rule.message,
            severity: rule.severity || 'warning',
          });
        }
      }
    }
  }

  // If content has synthetic voice or avatar, ensure audio/visual disclosure is flagged if required
  const hasSyntheticAudio = options?.hasAiVoice ?? true;
  const audioDisclaimer =
    ruleDef.audioDisclosureRequired && hasSyntheticAudio ? ruleDef.audioDisclaimerLocal : undefined;

  const requiredLabels: ComplianceRequiredLabels = {
    visualLabelText: ruleDef.mandatoryLabelEn,
    localLabelText: ruleDef.mandatoryLabelLocal,
    audioDisclaimerText: audioDisclaimer,
    position: ruleDef.defaultPosition,
    watermarkRequired: ruleDef.watermarkRequired,
    audioDisclosureRequired: ruleDef.audioDisclosureRequired,
  };

  const hasBlockingErrors = violations.some((v) => v.severity === 'error');

  return {
    jurisdiction,
    compliant: !hasBlockingErrors,
    violations,
    requiredLabels,
  };
}

// ─── Disclosure & Watermark Generator ─────────────────────────────────────────

export interface GeneratedAiDisclosure {
  visualLabel: {
    textEn: string;
    textLocal: string;
    position: DisclosurePosition;
    opacity: number;
    backgroundColor: string;
    textColor: string;
  };
  audioDisclaimer?: {
    textEn: string;
    textLocal: string;
    estimatedDurationSec: number;
  };
}

/**
 * Generate mandatory visual watermark and audio disclaimer metadata.
 */
export function generateAiDisclosure(
  jurisdiction: ComplianceJurisdiction,
  format: 'visual' | 'audio' | 'both' = 'both',
): GeneratedAiDisclosure {
  const ruleDef = JURISDICTION_RULES[jurisdiction] || JURISDICTION_RULES.GLOBAL;

  const visualLabel = {
    textEn: ruleDef.mandatoryLabelEn,
    textLocal: ruleDef.mandatoryLabelLocal,
    position: ruleDef.defaultPosition,
    opacity: 0.85,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    textColor: '#FFFFFF',
  };

  let audioDisclaimer: GeneratedAiDisclosure['audioDisclaimer'];
  if (format === 'audio' || format === 'both') {
    // Estimate speaking duration: roughly 3 words per second
    const wordCount = ruleDef.audioDisclaimerLocal.split(/\s+/).length;
    const estDuration = Math.max(1.5, Math.round((wordCount / 2.8) * 10) / 10);

    audioDisclaimer = {
      textEn: ruleDef.audioDisclaimerEn,
      textLocal: ruleDef.audioDisclaimerLocal,
      estimatedDurationSec: estDuration,
    };
  }

  return {
    visualLabel,
    audioDisclaimer,
  };
}

// ─── Automated Content Remediation ───────────────────────────────────────────

export interface RemediationResult {
  remediatedScript: string;
  replacements: Array<{
    original: string;
    replacement: string;
    ruleId: string;
    reason: string;
  }>;
}

/**
 * Automatically sanitize or replace non-compliant terms with legal alternatives.
 */
export function remediateContentCompliance(
  script: string,
  jurisdiction: ComplianceJurisdiction,
): RemediationResult {
  const ruleDef = JURISDICTION_RULES[jurisdiction] || JURISDICTION_RULES.GLOBAL;
  let remediated = script;
  const replacements: RemediationResult['replacements'] = [];

  for (const rule of ruleDef.forbiddenRules) {
    if (rule.safeReplacement) {
      remediated = remediated.replace(rule.regex, (match) => {
        replacements.push({
          original: match,
          replacement: rule.safeReplacement!,
          ruleId: rule.ruleId,
          reason: rule.message,
        });
        return rule.safeReplacement!;
      });
    }
  }

  return {
    remediatedScript: remediated,
    replacements,
  };
}

// ─── Audit Log Record Generator ───────────────────────────────────────────────

/**
 * Construct an immutable audit log record for persistence into `localized_content_audit_log`.
 */
export function createContentAuditRecord(params: {
  tenantId: string;
  videoId: string;
  jurisdiction: ComplianceJurisdiction;
  script: string;
  validationResult?: ComplianceValidationResult;
  auditedBy?: string;
}): ContentAuditRecord {
  const scan = params.validationResult || scanContentCompliance(params.script, params.jurisdiction);

  let status: ComplianceStatus = 'passed';
  if (!scan.compliant) {
    status = 'rejected';
  } else if (scan.violations.length > 0) {
    status = 'flagged';
  }

  const violationsDetected = scan.violations.map((v) => `[${v.ruleId}] ${v.matchedText}: ${v.message}`);

  // Generate unique UUID-compatible audit ID
  const randomPart = Math.random().toString(36).slice(2, 10);
  const auditId = `audit-${Date.now()}-${randomPart}`;

  return {
    id: auditId,
    tenantId: params.tenantId,
    videoId: params.videoId,
    regionCode: params.jurisdiction,
    complianceStatus: status,
    violationsDetected,
    remediationsApplied: [],
    aiLabelInjected: scan.requiredLabels.watermarkRequired,
    auditedBy: params.auditedBy || 'system_compliance_engine',
    createdAt: Date.now(),
  };
}
