/**
 * Solutions Catalog — 22+ Industry Profiles for Programmatic SEO Landing Pages.
 *
 * Provides high-converting bilingual copy, tailored pain points,
 * ready-to-run sample video prompts, ROI agency comparisons,
 * testimonials, and FAQs for sub-second SSG rendering.
 *
 * Layer: Seed (Configuration and static data, imports only seed)
 *
 * @module seed/config/solutions-catalog
 */

import type { SolutionIndustry } from '@/seed/types/solutions-types';
import { NICHE_LABELS, type NicheSlug } from '@/seed/config/niche-list';

export const PRIMARY_SOLUTIONS: SolutionIndustry[] = [
  {
    slug: 'real-estate',
    nameEn: 'Real Estate',
    nameVi: 'Bất Động Sản',
    category: 'High-Ticket Sales',
    iconName: 'Building2',
    heroHeadlineEn: 'Close Multi-Million Dollar Properties Faster With Automated AI Video Tours',
    heroHeadlineVi: 'Chốt Giao Dịch Nhà Đất Triệu Đô Nhanh Hơn Với Video Tour AI Tự Động',
    heroSubheadlineEn: 'Turn property photos and listing descriptions into cinematic walkthroughs, neighbourhood guides, and viral TikTok Reels in 60 seconds.',
    heroSubheadlineVi: 'Biến hình ảnh và mô tả dự án thành video walkthrough điện ảnh, review khu vực và clip viral TikTok chỉ trong 60 giây.',
    painPoints: [
      {
        titleEn: 'Exorbitant Video Production Costs',
        titleVi: 'Chi Phí Thuê Ekip Quay Phim Quá Đắt Đỏ',
        descEn: 'Traditional videography costs $1,500 - $3,000 per property with 2-week delays, losing hot buyer momentum.',
        descVi: 'Mỗi video quay nhà đất tốn 10 - 30 triệu VNĐ và mất 2 tuần hậu kỳ, làm nguội tệp khách mua tiềm năng.',
      },
      {
        titleEn: 'Repetitive Listing Explanations',
        titleVi: 'Tốn Hàng Giờ Lặp Lại Thông Tin Căn Hộ',
        descEn: 'Agents waste dozens of hours repeating square footage, zoning laws, and pricing to unqualified leads.',
        descVi: 'Môi giới mất hàng chục giờ lặp lại diện tích, pháp lý và giá cho những khách hàng chưa đủ tiêu chuẩn tài chính.',
      },
      {
        titleEn: 'Low Social Media Reach',
        titleVi: 'Kênh TikTok & Reels Thiếu Nội Dung Đều Đặn',
        descEn: 'Static images get buried by social algorithms that strictly prioritize daily short-form video content.',
        descVi: 'Hình ảnh tĩnh bị thuật toán bóp tương tác, nhường chỗ hoàn toàn cho các video ngắn đăng tải đều đặn mỗi ngày.',
      },
    ],
    samplePromptTitleEn: 'Luxury Penthouse Tour Hook & Breakdown',
    samplePromptTitleVi: 'Kịch Bản Hook Review Penthouse Triệu Đô',
    samplePromptEn: 'Create a 45-second high-energy luxury penthouse walkthrough in downtown, highlighting private elevator access, panoramic sunset terrace views, and exclusive 24/7 concierge amenities. Hook: "Would you spend $1.8M just for this elevator view?"',
    samplePromptVi: 'Tạo video 45 giây review căn Penthouse view sông đẳng cấp: thang máy riêng, ban công ngắm hoàng hôn 360 độ và tiện ích đặc quyền. Mở đầu bằng câu hook: "Liệu bạn có sẵn sàng chi 45 tỷ chỉ để sở hữu góc thang máy này?"',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3200,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 3001,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'Sophia AI helped our agency generate 38 qualified buyer inquiries in 30 days without hiring a single cameraman.',
      quoteVi: 'Sophia AI giúp sàn bất động sản của tôi chốt 38 khách nét trong 30 ngày mà không cần thuê bất kỳ thợ quay nào.',
      author: 'Marcus Vance',
      roleEn: 'Managing Broker',
      roleVi: 'Giám Đốc Kinh Doanh Sàn',
      company: 'Vance Prestige Realty',
      metrics: '+340% inbound inquiries in 30 days',
    },
    faqs: [
      {
        questionEn: 'Can I generate videos using only property photos?',
        questionVi: 'Tôi có thể tạo video chỉ từ hình ảnh căn hộ chụp bằng điện thoại không?',
        answerEn: 'Yes! Sophia AI Factory automatically analyzes property photos, enhances lighting, stitches cinematic transitions, and adds AI voiceover with synced subtitles.',
        answerVi: 'Hoàn toàn được! Sophia AI Factory tự động xử lý ảnh, tạo chuyển cảnh điện ảnh mượt mà, lồng tiếng AI truyền cảm và chèn phụ đề tự động.',
      },
      {
        questionEn: 'Does Sophia support Vietnamese voiceover accents?',
        questionVi: 'Sophia có hỗ trợ giọng đọc tiếng Việt Bắc/Nam chuẩn không?',
        answerEn: 'Yes, Sophia supports 50+ hyper-natural voices including Northern and Southern Vietnamese regional tones with natural emotional inflections.',
        answerVi: 'Có, Sophia tích hợp hơn 50 giọng đọc tự nhiên bao gồm cả giọng Hà Nội và Sài Gòn với ngữ điệu bán hàng chuyên nghiệp.',
      },
      {
        questionEn: 'How does the Telegram bot lead qualification work?',
        questionVi: 'Tính năng phân loại khách hàng qua Telegram Bot hoạt động ra sao?',
        answerEn: 'A deep-link in your video caption routes buyers directly into our automated qualification bot to collect budget, preferred location, and timing before alerting you.',
        answerVi: 'Đường link trong video dẫn khách thẳng vào Bot Telegram để khảo sát ngân sách, khu vực mong muốn và thời điểm mua rồi gửi thông báo ngay cho bạn.',
      },
    ],
    keywordsEn: ['real estate ai video', 'property listing video generator', 'realtor tiktok marketing', 'automated property tours'],
    keywordsVi: ['video bất động sản ai', 'tạo video bán nhà tự động', 'marketing bđs tiktok', 'review căn hộ tự động'],
  },

  {
    slug: 'cosmetics',
    nameEn: 'Cosmetics & Beauty',
    nameVi: 'Mỹ Phẩm & Thẩm Mỹ',
    category: 'E-Commerce & Retail',
    iconName: 'Sparkles',
    heroHeadlineEn: 'Viral Beauty Demos & Skincare Transformations That Sell Out Inventory',
    heroHeadlineVi: 'Video Biến Hình Mỹ Phẩm & Skincare Viral Cháy Hàng Trong Tích Tắc',
    heroSubheadlineEn: 'Produce hundreds of thumb-stopping before/after reels, ingredient breakdowns, and UGC-style reviews tailored for TikTok Shop and Shopee.',
    heroSubheadlineVi: 'Tự động xuất hàng trăm video biến hình trước/sau, giải mã thành phần và review chân thực chuẩn UGC cho TikTok Shop và Shopee.',
    painPoints: [
      {
        titleEn: 'High KOC / Influencer Booking Fees',
        titleVi: 'Phí Thuê KOC & Beauty Blogger Đắt Đỏ',
        descEn: 'Beauty influencers charge $500 - $2,000 per video with zero guarantee of viral views or sales conversion.',
        descVi: 'Thuê một KOC review tốn từ 10 - 50 triệu/clip nhưng không cam kết ra đơn hay view.',
      },
      {
        titleEn: 'Strict Advertising Compliance Bans',
        titleVi: 'Tài Khoản Dễ Bị Khóa Do Vi Phạm Quảng Cáo',
        descEn: 'Ad accounts get banned for non-compliant claim wording without automated compliance scanning.',
        descVi: 'Nhiều video bị TikTok bóp tương tác do vi phạm chính sách cam kết hiệu quả quá đà.',
      },
      {
        titleEn: 'High Creative Fatigue',
        titleVi: 'Mẫu Video Nhanh Chóng Bị Bão Hòa',
        descEn: 'Beauty ad creatives fatigue within 7 days, demanding a relentless stream of fresh hooks and visual variations.',
        descVi: 'Mỗi mẫu video chỉ chạy hiệu quả 5-7 ngày là cạn tương tác, đòi hỏi liên tục sản xuất góc quay mới.',
      },
    ],
    samplePromptTitleEn: 'Retinol Serum Before & After UGC Script',
    samplePromptTitleVi: 'Kịch Bản UGC Serum Niacinamide Giảm Thâm',
    samplePromptEn: 'Generate a 30-second TikTok UGC-style testimonial addressing stubborn acne marks. Hook: "If you are still scrubbing your skin with physical exfoliants in 2026, stop right now!" Emphasize visible glow in 14 days with clinical ingredient proof.',
    samplePromptVi: 'Tạo video ngắn 30s phong cách KOC chia sẻ kinh nghiệm xử lý thâm mụn. Hook: "Nếu 2026 bạn vẫn còn dùng tẩy tế bào chết hạt to, dừng ngay lại trước khi rách da!" Trình bày thành phần 10% Niacinamide và kết quả sau 14 ngày.',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2800,
      traditionalTurnaroundDays: 10,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 45,
      estimatedMonthlySavingsUsd: 2601,
      estimatedVideoOutputPerMonth: 80,
    },
    testimonial: {
      quoteEn: 'Our TikTok Shop GMV tripled in two weeks after launching 5 daily Sophia-generated skincare hooks.',
      quoteVi: 'Doanh số TikTok Shop của thương hiệu mỹ phẩm chúng tôi tăng gấp 3 sau khi đăng đều đặn 5 video mỗi ngày từ Sophia.',
      author: 'Chloe Nguyen',
      roleEn: 'Head of Growth',
      roleVi: 'Trưởng Phòng Tăng Trưởng',
      company: 'Aura Derma Lab',
      metrics: '3.2x GMV growth on TikTok Shop',
    },
    faqs: [
      {
        questionEn: 'Can I insert my actual product packaging into generated videos?',
        questionVi: 'Tôi có thể đưa bao bì sản phẩm thật vào video không?',
        answerEn: 'Yes, simply upload your transparent product PNG and Sophia will seamlessly composite it into realistic lifestyle scenes.',
        answerVi: 'Được chứ, chỉ cần tải lên ảnh sản phẩm tách nền, Sophia sẽ ghép tự nhiên vào bối cảnh đời thực và bàn trang điểm.',
      },
      {
        questionEn: 'How does Sophia ensure video claims comply with advertising policies?',
        questionVi: 'Sophia có kiểm duyệt từ ngữ tránh bị bóp tương tác không?',
        answerEn: 'Sophia built-in content filters automatically detect and suggest safe phrasing to protect your TikTok ad accounts from policy bans.',
        answerVi: 'Bộ lọc nội dung của Sophia tự động gợi ý cách dùng từ chuẩn chính sách để video không bị quét từ cấm trên TikTok/Facebook.',
      },
    ],
    keywordsEn: ['beauty ai video generator', 'skincare tiktok ads', 'cosmetics ugc video maker', 'tiktok shop beauty marketing'],
    keywordsVi: ['làm video mỹ phẩm ai', 'quảng cáo skincare tiktok', 'ugc review mỹ phẩm', 'tăng doanh số tiktok shop'],
  },

  {
    slug: 'fashion',
    nameEn: 'Fashion & Apparel',
    nameVi: 'Thời Trang & Phụ Kiện',
    category: 'E-Commerce & Retail',
    iconName: 'Shirt',
    heroHeadlineEn: 'Runway Lookbooks & Outfit Transformations In Seconds Without Photo Studios',
    heroHeadlineVi: 'Xuất Hàng Loạt Video Biến Hình OOTD Thời Trang Không Cần Thuê Studio',
    heroSubheadlineEn: 'Transform flat-lay apparel images into dynamic runway walk models, trending styling challenges, and viral haul videos.',
    heroSubheadlineVi: 'Biến ảnh chụp sản phẩm trải phẳng thành video người mẫu catwalk sống động, phối đồ theo xu hướng và clip thử đồ triệu view.',
    painPoints: [
      {
        titleEn: 'High Model & Studio Rentals',
        titleVi: 'Chi Phí Thuê Mẫu & Studio Quá Lớn',
        descEn: 'Studio sessions cost thousands per collection with long editing lead times while micro-trends fade.',
        descVi: 'Mỗi buổi chụp/quay lookbook tốn 15-20 triệu nhưng khi ra video thì trend đã nguội.',
      },
      {
        titleEn: 'Rapid Trend Cycle Obsolescence',
        titleVi: 'Xu Hướng Thay Đổi Quá Nhanh',
        descEn: 'Fast fashion trends change weekly; traditional editing pipelines are too slow to capitalize on virality.',
        descVi: 'Mỗi tuần lại có trend phối đồ mới; làm thủ công không kịp bắt nhịp thuật toán.',
      },
      {
        titleEn: 'High Return Rates Due to Fit Concerns',
        titleVi: 'Tỉ Lệ Trả Hàng Do Khách Không Hình Dung Được Form',
        descEn: 'Customers return items when static photos fail to show fabric drape, texture, and natural movement.',
        descVi: 'Khách hàng phân vân không biết vải rủ hay đứng form thế nào nếu chỉ xem ảnh tĩnh.',
      },
    ],
    samplePromptTitleEn: 'Autumn Capsule Wardrobe Styling 3 Looks',
    samplePromptTitleVi: '3 Cách Phối Áo Blazer Đi Làm & Đi Chơi',
    samplePromptEn: 'Create a 25-second fast-paced styling reel showcasing 1 oversized blazer styled 3 distinct ways: corporate chic, casual coffee run, and evening drinks. Hook: "One blazer, zero excuses to say you have nothing to wear."',
    samplePromptVi: 'Tạo video 25 giây chuyển cảnh nhanh 3 outfit phối với 1 chiếc blazer: công sở thanh lịch, dạo phố cuối tuần và tiệc tối. Hook: "Chỉ 1 chiếc blazer này, từ nay khỏi lo không biết mặc gì ra đường."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2500,
      traditionalTurnaroundDays: 7,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2301,
      estimatedVideoOutputPerMonth: 90,
    },
    testimonial: {
      quoteEn: 'Sophia allowed us to launch 30 new SKUs in a month with unique video reels for every single garment.',
      quoteVi: 'Sophia cho phép thương hiệu chúng tôi ra mắt 30 mẫu mới mỗi tháng với video phối đồ riêng cho từng mẫu.',
      author: 'Vy Tran',
      roleEn: 'Creative Director',
      roleVi: 'Giám Đốc Sáng Tạo',
      company: 'Maison Minimal',
      metrics: '30 SKUs launched with 90 video assets in 1 month',
    },
    faqs: [
      {
        questionEn: 'Can Sophia animate garments onto different body types?',
        questionVi: 'Sophia có thể tạo mẫu người nhiều dáng vóc khác nhau không?',
        answerEn: 'Yes, you can specify model demographics, heights, and body profiles to showcase inclusive sizing.',
        answerVi: 'Có, bạn có thể chỉ định người mẫu theo nhiều vóc dáng và chiều cao để khách hàng dễ chọn size.',
      },
    ],
    keywordsEn: ['fashion ai video', 'lookbook video generator', 'ootd tiktok creator', 'apparel ecommerce video'],
    keywordsVi: ['video thời trang ai', 'tạo lookbook tự động', 'clip biến hình ootd', 'quảng cáo quần áo tiktok'],
  },

  {
    slug: 'courses',
    nameEn: 'Online Courses & E-Learning',
    nameVi: 'Khóa Học Trực Tuyến & E-Learning',
    category: 'Knowledge Commerce',
    iconName: 'GraduationCap',
    heroHeadlineEn: 'Turn High-Value Knowledge Into High-Enrollment Student Funnels',
    heroHeadlineVi: 'Biến Kiến Thức Chuyên Môn Thành Phễu Tuyển Sinh Trực Tuyến Tự Động',
    heroSubheadlineEn: 'Generate magnetic micro-lesson hooks, case study breakdowns, and automated webinar promos that fill coaching cohorts on autopilot.',
    heroSubheadlineVi: 'Tự động tạo video bài học ngắn thu hút, phân tích ca thực tế và clip mời tham gia webinar tuyển sinh cho lớp học của bạn.',
    painPoints: [
      {
        titleEn: 'Struggling to Fill Cohorts',
        titleVi: 'Khó Khăn Trong Việc Tuyển Đủ Học Viên',
        descEn: 'Experts spend months building great curriculums but struggle to consistently generate enrolled leads.',
        descVi: 'Chuyên gia mất hàng tháng soạn giáo trình nhưng không biết cách kéo học viên đăng ký đều đặn.',
      },
      {
        titleEn: 'Camera Shyness and Recording Fatigue',
        titleVi: 'Ngại Đứng Trước Máy Quay & Tốn Thời Gian',
        descEn: 'Instructors burn out after hours of speaking to a camera, editing retakes, and fixing audio mistakes.',
        descVi: 'Nhiều giảng viên mất hàng giờ ghi hình, nói vấp phải quay lại và mất công cắt ghép.',
      },
      {
        titleEn: 'Rising Paid Ad Lead Costs',
        titleVi: 'Chi Phí Chạy Quảng Cáo Facebook Quá Đắt',
        descEn: 'Cost per lead on Meta ads has surged 200%, demanding organic video hooks to drive down blended CPA.',
        descVi: 'Giá lead quảng cáo Facebook ngày càng đắt, cần video ngắn kéo traffic tự nhiên để giảm giá vốn.',
      },
    ],
    samplePromptTitleEn: 'Actionable 60-Second Framework Mini-Lesson',
    samplePromptTitleVi: 'Kịch Bản Bài Học Ngắn 60s Giải Quyết Vấn Đề',
    samplePromptEn: 'Create a 60-second micro-lesson explaining the 3 common mistake beginners make in financial accounting. Hook: "If you are still calculating your net profit this way, you are lying to your investors." Call to action: Comment "AUDIT" to receive the free spreadsheet template.',
    samplePromptVi: 'Tạo video ngắn 60s chia sẻ 3 sai lầm chí mạng khi lập kế hoạch tài chính. Hook: "Nếu bạn vẫn tính điểm hòa vốn kiểu này, bạn đang đốt sạch vốn mà không hề biết." Kêu gọi hành động: Nhắn tin nhận bảng tính mẫu miễn phí.',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2200,
      traditionalTurnaroundDays: 10,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2001,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'I booked out my $2,000 cohort in 12 days purely using Sophia-generated bite-sized lesson shorts on YouTube.',
      quoteVi: 'Khóa coaching 20 triệu của tôi kín chỗ trong 12 ngày hoàn toàn nhờ các video bài học ngắn do Sophia tạo trên YouTube Shorts.',
      author: 'David Le',
      roleEn: 'Course Creator & Consultant',
      roleVi: 'Chuyên Gia Đào Tạo Doanh Nghiệp',
      company: 'GrowthMastery Academy',
      metrics: '42 new students enrolled in 12 days',
    },
    faqs: [
      {
        questionEn: 'Can I clone my own voice for teaching videos?',
        questionVi: 'Tôi có thể dùng chính giọng nói của mình để lồng tiếng không?',
        answerEn: 'Yes! Sophia provides instant voice cloning from a 30-second audio sample so your videos sound 100% authentically yours.',
        answerVi: 'Chính xác! Sophia hỗ trợ nhân bản giọng nói chỉ với 30 giây mẫu thu âm để giữ đúng chất giọng cá nhân của bạn.',
      },
    ],
    keywordsEn: ['course creator ai video', 'educational reels generator', 'youtube shorts for teachers', 'elearning marketing'],
    keywordsVi: ['làm video khóa học', 'tuyển sinh tự động bằng ai', 'bài giảng ngắn youtube shorts', 'marketing giáo dục'],
  },

  {
    slug: 'f-and-b',
    nameEn: 'Food & Beverage',
    nameVi: 'F&B & Nhà Hàng',
    category: 'Local Hospitality',
    iconName: 'Utensils',
    heroHeadlineEn: 'Mouthwatering Culinary Reels That Pack Tables Every Weekend',
    heroHeadlineVi: 'Video Món Ăn Chảy Nước Miếng Kéo Khách Kín Bàn Mỗi Cuối Tuần',
    heroSubheadlineEn: 'Showcase sizzling dishes, mixology secrets, and chef specials with irresistible sensory pacing and background ambient audio.',
    heroSubheadlineVi: 'Trình diễn những đĩa thức ăn bốc khói nghi ngút, bí quyết pha chế và món đặc sắc của bếp trưởng với âm thanh ASMR kích thích vị giác.',
    painPoints: [
      {
        titleEn: 'Empty Tables on Weekdays',
        titleVi: 'Vắng Khách Vào Các Ngày Đầu Tuần',
        descEn: 'Restaurants struggle with low weekday footfall while fixed staff and rent overhead remain constant.',
        descVi: 'Nhà hàng vắng khách thứ 2 - thứ 5 trong khi chi phí nhân viên và mặt bằng vẫn phải trả đủ.',
      },
      {
        titleEn: 'High Food Reviewer Sponsorship Costs',
        titleVi: 'Chi Phí Thuê Food Reviewer Tốn Kém',
        descEn: 'Local food reviewers demand free dining plus hefty sponsorship fees for unpredictable reach.',
        descVi: 'Mời reviewer đến ăn tốn tiền triệu tiền món cộng thêm phí catxe nhưng lượng khách quay lại không bền.',
      },
      {
        titleEn: 'Failure to Convey Food Appeal in Stills',
        titleVi: 'Ảnh Menu Tĩnh Không Truyền Tải Được Độ Ngon',
        descEn: 'Static menu photos fail to evoke the sizzling sound, cheese pulls, and steam that trigger hunger cravings.',
        descVi: 'Ảnh chụp món đơn thuần không diễn tả được cảnh phô mai kéo sợi, nước sốt sôi sùng sục và khói thơm.',
      },
    ],
    samplePromptTitleEn: 'Sizzling Ribeye Steak ASMR Special',
    samplePromptTitleVi: 'Video Món Bò Bít Tết Nướng Sốt Nấm ASMR',
    samplePromptEn: 'Create a 20-second sensory-rich video highlighting an A5 Wagyu ribeye hitting a 500-degree cast-iron skillet, garlic butter basting, and knife slicing tenderly. Hook: "Hear that sound? That is your dinner calling you tonight."',
    samplePromptVi: 'Tạo video 20s kích thích vị giác quay cận cảnh miếng bò Wagyu áp chảo gang rưới bơ tỏi thơm lừng, cắt từng thớ thịt mọng nước. Hook: "Âm thanh xèo xèo này chính là lý do tối nay bạn phải rủ người thương đi ăn."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 1800,
      traditionalTurnaroundDays: 7,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 45,
      estimatedMonthlySavingsUsd: 1601,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'We gained 4,500 new local followers and completely booked out our weekend reservations in month one.',
      quoteVi: 'Quán ăn của chúng tôi tăng 4.500 người theo dõi địa phương và kín bàn đặt trước suốt cả tháng qua video AI.',
      author: 'Chef Hai Nguyen',
      roleEn: 'Executive Chef & Owner',
      roleVi: 'Bếp Trưởng & Đồng Sáng Lập',
      company: 'The Rustic Table Kitchen',
      metrics: '+85% table reservations on weekdays',
    },
    faqs: [
      {
        questionEn: 'Can I add our restaurant address and Google Maps link to the video CTA?',
        questionVi: 'Tôi có thể gắn địa chỉ và link Google Maps vào video không?',
        answerEn: 'Yes, Sophia automatically renders location stickers, opening hours, and direct booking buttons onto your video overlays.',
        answerVi: 'Được chứ, Sophia tự động chèn thông tin địa chỉ, giờ mở cửa và nút điều hướng xem bản đồ hoặc đặt bàn.',
      },
    ],
    keywordsEn: ['restaurant marketing video', 'food reels generator', 'culinary tiktok video', 'cafe promotion ai'],
    keywordsVi: ['làm video quán ăn', 'quảng cáo nhà hàng tiktok', 'video review ẩm thực', 'marketing f&b tự động'],
  },

  {
    slug: 'insurance',
    nameEn: 'Insurance',
    nameVi: 'Bảo Hiểm',
    category: 'Financial Services',
    iconName: 'ShieldCheck',
    heroHeadlineEn: 'De-Mystify Complex Policies & Sign More Policyholders With Compassionate Video',
    heroHeadlineVi: 'Giải Thích Điều Khoản Dễ Hiểu & Tư Vấn Hợp Đồng Bảo Hiểm Nhanh Chóng',
    heroSubheadlineEn: 'Turn confusing policy legalese into compassionate case studies, financial security roadmaps, and instant trust builders.',
    heroSubheadlineVi: 'Biến những điều khoản khô khan thành câu chuyện bảo vệ gia đình chân thực, minh bạch quyền lợi bồi thường và xây dựng lòng tin.',
    painPoints: [
      {
        titleEn: 'Low Consumer Trust and High Skepticism',
        titleVi: 'Khách Hàng Còn E Ngại & Nghi Ngờ Bảo Hiểm',
        descEn: 'Prospects dread sales pitches and assume insurance contracts hide predatory fine print.',
        descVi: 'Khách thường sợ bị chèo kéo và lo ngại hợp đồng có các điều khoản loại trừ khó hiểu.',
      },
      {
        titleEn: 'Complex Products Hard to Explain Briefly',
        titleVi: 'Sản Phẩm Phức Tạp Khó Truyền Đạt Trong Vài Phút',
        descEn: 'Explaining riders, surrender values, and critical illness tiers usually requires tedious meetings.',
        descVi: 'Giải thích quyền lợi nội trú, bệnh hiểm nghèo và giá trị hoàn lại tốn nhiều buổi gặp mặt.',
      },
      {
        titleEn: 'High Agent Attrition Due to Rejection',
        titleVi: 'Đại Lý Dễ Bỏ Cuộc Vì Bị Từ Chối Quá Nhiều',
        descEn: 'Cold calling and door-to-door prospecting yield high rejection and fast agent burnout.',
        descVi: 'Tìm kiếm khách hàng bằng gọi điện thoại lạnh khiến tư vấn viên mệt mỏi và dễ nản lòng.',
      },
    ],
    samplePromptTitleEn: 'Critical Illness Protection Myth Debunked',
    samplePromptTitleVi: 'Giải Đáp Thắc Mắc Quyền Lợi Bệnh Hiểm Nghèo',
    samplePromptEn: 'Create a 45-second educational video addressing the misconception: "I am young and healthy, so I do not need insurance." Break down real medical inflation numbers and show how a $3/day plan preserves family savings.',
    samplePromptVi: 'Tạo video ngắn 45s gỡ bỏ rào cản: "Còn trẻ khỏe thì cần gì mua bảo hiểm". Đưa ra số liệu viện phí thực tế và chứng minh chỉ với 50k/ngày đã bảo vệ cả tương lai tài chính gia đình.',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2600,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2401,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'I went from struggling with cold calls to receiving 15 warm consultation bookings every week from my TikTok videos.',
      quoteVi: 'Từ chỗ gọi điện thoại bị từ chối liên tục, giờ đây mỗi tuần tôi có 15 khách chủ động nhắn tin nhờ tư vấn hợp đồng bảo hiểm.',
      author: 'Lan Huong Tran',
      roleEn: 'MDRT Financial Consultant',
      roleVi: 'Chuyên Viên Tư Vấn Tài Chính MDRT',
      company: 'Apex Life Partners',
      metrics: '15 warm consultation calls booked weekly',
    },
    faqs: [
      {
        questionEn: 'Are the scripts compliant with insurance marketing regulations?',
        questionVi: 'Nội dung video có tuân thủ quy định truyền thông ngành bảo hiểm không?',
        answerEn: 'Yes, Sophia includes disclaimer presets and ethical messaging templates designed for licensed insurance advisors.',
        answerVi: 'Có, các mẫu kịch bản của Sophia luôn tích hợp sẵn các lưu ý miễn trừ trách nhiệm và câu chữ minh bạch chuẩn ngành.',
      },
    ],
    keywordsEn: ['insurance marketing video', 'life insurance reels', 'financial advisor tiktok', 'insurance lead generation'],
    keywordsVi: ['marketing bảo hiểm nhân thọ', 'video tư vấn tài chính', 'tìm khách mua bảo hiểm', 'kịch bản video bảo hiểm'],
  },

  {
    slug: 'fitness',
    nameEn: 'Fitness & Gym',
    nameVi: 'Thể Hình & Gym',
    category: 'Health & Wellness',
    iconName: 'Dumbbell',
    heroHeadlineEn: 'Inspiring Body Transformations That Fill Personal Training Rosters',
    heroHeadlineVi: 'Video Biến Hình Thể Hình Đầy Cảm Hứng Giúp PT Kín Lịch Dạy',
    heroSubheadlineEn: 'Produce high-octane workout routines, nutritional meal preps, and genuine client transformation reels that convert gym-goers into committed PT clients.',
    heroSubheadlineVi: 'Xuất các video bài tập chuẩn form, thực đơn giảm mỡ và câu chuyện thay đổi vóc dáng ngoạn mục để thu hút học viên mới.',
    painPoints: [
      {
        titleEn: 'High Gym Membership Churn',
        titleVi: 'Hội Viên Thường Bỏ Tập Sau Tháng Đầu Tiên',
        descEn: 'Gyms lose up to 50% of members within 90 days without motivational follow-ups and guidance.',
        descVi: 'Nhiều người bỏ dở sau vài tuần vì không có động lực và chưa nắm rõ lộ trình tập.',
      },
      {
        titleEn: 'Trainers Wasting Time Filming Themselves',
        titleVi: 'Huấn Luyện Viên Tốn Thời Gian Tự Quay Tự Sửa',
        descEn: 'PTs spend gym floor hours struggling with tripods and video editing instead of training paying clients.',
        descVi: 'PT mất hàng giờ loay hoay dựng chân máy quay clip thay vì tập trung huấn luyện học viên có phí.',
      },
      {
        titleEn: 'Price Wars With Cheap Commercial Gyms',
        titleVi: 'Bị Cạnh Tranh Gay Gắt Về Giá Vé Tập',
        descEn: 'Personal coaching is commoditized unless trainers clearly demonstrate personalized methodology through video.',
        descVi: 'Nếu không chứng minh được chuyên môn bằng video, bạn sẽ dễ bị ép giá với các phòng tập giá rẻ.',
      },
    ],
    samplePromptTitleEn: '3 Common Squat Form Mistakes Hurting Your Knees',
    samplePromptTitleVi: '3 Lỗi Sai Khi Squat Khiến Bạn Đau Khớp Gối',
    samplePromptEn: 'Create a 30-second form correction reel showing side-by-side: incorrect knee cave vs proper hip-hinge squat technique. Hook: "If your knees hurt after leg day, you are making this fatal mistake."',
    samplePromptVi: 'Tạo video ngắn 30s sửa tư thế: So sánh trực quan lỗi khép gối khi Squat và cách gồng core đúng. Hook: "Nếu tập chân xong mà đau đầu gối thay vì mỏi đùi, bạn đang mắc lỗi nghiêm trọng này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2000,
      traditionalTurnaroundDays: 7,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 45,
      estimatedMonthlySavingsUsd: 1801,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'I added 12 new 1-on-1 personal training clients in my first month using automated workout tip reels.',
      quoteVi: 'Tôi nhận thêm 12 học viên kèm 1-1 ngay trong tháng đầu nhờ chia sẻ mẹo tập luyện do Sophia tự động sản xuất.',
      author: 'Coach Alex Doan',
      roleEn: 'Head Strength Coach',
      roleVi: 'Huấn Luyện Viên Trưởng',
      company: 'IronClad Performance',
      metrics: '+12 private PT clients recruited',
    },
    faqs: [
      {
        questionEn: 'Can Sophia generate calorie and nutrition meal plan explainers?',
        questionVi: 'Sophia có thể tạo video hướng dẫn tính calo và meal prep không?',
        answerEn: 'Yes! Sophia creates clear graphic overlays for macronutrient counts, meal preparation steps, and healthy recipes.',
        answerVi: 'Rất tốt! Sophia tự động chèn bảng tính macro, calo từng bữa ăn và hướng dẫn chế biến nhanh gọn.',
      },
    ],
    keywordsEn: ['fitness reels generator', 'personal trainer tiktok marketing', 'gym workout video ai', 'transformation video maker'],
    keywordsVi: ['làm video gym thể hình', 'quảng cáo pt kèm riêng', 'hướng dẫn tập luyện tiktok', 'video giảm cân giảm mỡ'],
  },

  {
    slug: 'lawyer',
    nameEn: 'Legal & Attorney',
    nameVi: 'Luật Sư & Tư Vấn Pháp Lý',
    category: 'Professional Services',
    iconName: 'Scale',
    heroHeadlineEn: 'Authoritative Legal Breakdown Videos That Establish Market Trust & Win Retainers',
    heroHeadlineVi: 'Video Phân Tích Pháp Luật Chuẩn Mực Xây Dựng Uy Tín & Ký Hợp Đồng Thân Chủ',
    heroSubheadlineEn: 'Explain complex contract disputes, inheritance regulations, and business compliance laws with authoritative clarity that turns viewers into retained clients.',
    heroSubheadlineVi: 'Giải thích tranh chấp hợp đồng, thủ tục thừa kế và luật doanh nghiệp với phong thái đĩnh đạc, biến người xem thành thân chủ trung thành.',
    painPoints: [
      {
        titleEn: 'Strict Bar Association Marketing Restrictions',
        titleVi: 'Rào Cản Quy Định Quảng Cáo Ngành Luật',
        descEn: 'Law firms cannot run loud, flashy ads; they must win clients purely through demonstrable expertise.',
        descVi: 'Luật sư không thể quảng cáo phản cảm; uy tín chỉ đến từ việc chia sẻ kiến thức pháp lý sâu sắc.',
      },
      {
        titleEn: 'Prospects Unaware They Need Legal Counsel',
        titleVi: 'Khách Hàng Chưa Nhận Thức Được Rủi Ro Pháp Lý',
        descEn: 'Most businesses only contact a lawyer after a catastrophic breach has already occurred.',
        descVi: 'Nhiều chủ doanh nghiệp chỉ tìm đến luật sư khi tranh chấp đã xảy ra và thiệt hại hàng tỷ đồng.',
      },
      {
        titleEn: 'Expensive Billable Hours Wasted on Basic Consults',
        titleVi: 'Mất Nhiều Giờ Giải Thích Những Vấn Đề Cơ Bản',
        descEn: 'Senior partners burn valuable hours answering routine legal questions instead of working high-fee litigation.',
        descVi: 'Luật sư cao cấp tốn thời gian trả lời những câu hỏi cơ bản thay vì tập trung vào các vụ kiện lớn.',
      },
    ],
    samplePromptTitleEn: '3 Costly Mistakes Founders Make in Co-Founder Agreements',
    samplePromptTitleVi: '3 Lỗi Chết Người Khi Ký Hợp Đồng Cổ Đông Sáng Lập',
    samplePromptEn: 'Create a 45-second high-credibility legal video warning tech founders about vesting schedules, voting deadlocks, and intellectual property assignment. Hook: "Before you split equity 50/50 with your best friend, watch this."',
    samplePromptVi: 'Tạo video ngắn 45s lưu ý các nhà sáng lập: Điều khoản chia cổ phần vesting, biểu quyết bế tắc và quyền sở hữu trí tuệ. Hook: "Trước khi chia đôi 50/50 cổ phần với bạn thân, hãy xem hết video này để tránh mất quyền kiểm soát."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3500,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 3301,
      estimatedVideoOutputPerMonth: 40,
    },
    testimonial: {
      quoteEn: 'A single 45-second corporate compliance reel generated a $15,000 annual retainer from a logistics company.',
      quoteVi: 'Chỉ một video 45 giây phân tích hợp đồng thương mại đã giúp văn phòng luật của tôi ký hợp đồng tư vấn thường xuyên trị giá 350 triệu/năm.',
      author: 'Attorney Vu Quang',
      roleEn: 'Managing Partner',
      roleVi: 'Luật Sư Điều Hành',
      company: 'Quang & Associates Law',
      metrics: '+$15K corporate retainer acquired',
    },
    faqs: [
      {
        questionEn: 'How does Sophia ensure the legal tone remains dignified and professional?',
        questionVi: 'Sophia có đảm bảo phong thái trang trọng, chuẩn mực ngành luật không?',
        answerEn: 'Sophia uses executive color grading, professional presenter avatars, and measured vocal pacing calibrated specifically for legal professionals.',
        answerVi: 'Sophia thiết lập sẵn bảng màu trang trọng, âm sắc đĩnh đạc và kịch bản súc tích phù hợp hoàn hảo với giới luật gia.',
      },
    ],
    keywordsEn: ['legal marketing video', 'lawyer reels generator', 'attorney tiktok', 'law firm lead generation'],
    keywordsVi: ['marketing văn phòng luật', 'video luật sư tư vấn', 'kiến thức pháp luật tiktok', 'tìm khách hàng dịch vụ luật'],
  },

  {
    slug: 'saas',
    nameEn: 'SaaS & B2B Software',
    nameVi: 'Phần Mềm SaaS & B2B',
    category: 'Technology',
    iconName: 'Laptop',
    heroHeadlineEn: 'Convert Cold Product Demos Into Product-Led Growth ARR Explosions',
    heroHeadlineVi: 'Biến Video Demo Tính Năng Thành Cỗ Máy Tăng Trưởng ARR Tự Động',
    heroSubheadlineEn: 'Produce snappy feature walkthroughs, UI micro-interactions, and problem-solution teardowns that get developer and enterprise trials instantly.',
    heroSubheadlineVi: 'Tạo video giới thiệu tính năng, tương tác giao diện và giải pháp công nghệ trực quan giúp tăng tỉ lệ đăng ký dùng thử ngay lập tức.',
    painPoints: [
      {
        titleEn: 'Low Demo-to-Trial Conversion',
        titleVi: 'Khách Đọc Landing Page Nhưng Không Dùng Thử',
        descEn: 'Visitors bounce off walls of text and static feature screenshots without understanding the core workflow.',
        descVi: 'Khách rời trang web vì các đoạn mô tả tính năng quá dài dòng, không hình dung được sản phẩm giải quyết việc gì.',
      },
      {
        titleEn: 'Long Sales Cycles for B2B Buyers',
        titleVi: 'Chu Kỳ Bán Hàng B2B Kéo Dài',
        descEn: 'Convincing decision-makers takes dozens of meetings when asynchronous video teardowns could close the gap.',
        descVi: 'Chốt hợp đồng doanh nghiệp mất nhiều tuần nếu không có video demo ngắn gọn gửi cho các cấp phê duyệt.',
      },
      {
        titleEn: 'High Customer Success Onboarding Load',
        titleVi: 'Nhóm Hỗ Trợ Quá Tải Hướng Dẫn Sử Dụng',
        descEn: 'Users churn early when initial product setup lacks step-by-step video guidance.',
        descVi: 'Người dùng bỏ cuộc nếu gặp khó khăn trong bước thiết lập ban đầu mà không có video trực quan.',
      },
    ],
    samplePromptTitleEn: '30-Second API Automation Workflow Teardown',
    samplePromptTitleVi: 'Kịch Bản Demo Tự Động Hóa Dữ Liệu Trong 30s',
    samplePromptEn: 'Create a 30-second developer-focused teardown showing manual webhook syncing vs our 1-click cloud sync. Hook: "Still writing custom cron jobs to sync Stripe with your database? Watch this 3-line shortcut."',
    samplePromptVi: 'Tạo video ngắn 30s cho lập trình viên: So sánh việc viết code cron job thủ công với tính năng đồng bộ 1 chạm. Hook: "Nếu bạn vẫn đang mất cả buổi viết webhook đồng bộ dữ liệu, xem ngay giải pháp 3 dòng lệnh này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3000,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2801,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'Our self-serve trial signups jumped by 47% after embedding Sophia walkthrough reels across our feature docs.',
      quoteVi: 'Lượng đăng ký dùng thử phần mềm của chúng tôi tăng 47% sau khi chèn các video hướng dẫn ngắn do Sophia tạo vào trang sản phẩm.',
      author: 'Victor Chen',
      roleEn: 'Co-Founder & CTO',
      roleVi: 'Đồng Sáng Lập & CTO',
      company: 'SyncPulse API',
      metrics: '+47% trial signup conversion rate',
    },
    faqs: [
      {
        questionEn: 'Can Sophia integrate with screen recording clips of our software?',
        questionVi: 'Tôi có thể tải video quay màn hình giao diện app của mình lên không?',
        answerEn: 'Yes, upload your Loom or raw MP4 recordings and Sophia will automatically zoom in on clicks, add subtitles, and voice the narration.',
        answerVi: 'Có, bạn chỉ cần tải video quay màn hình, Sophia sẽ tự động phóng to con trỏ chuột, chèn phụ đề nổi bật và lồng tiếng giải thích.',
      },
    ],
    keywordsEn: ['saas product video', 'software demo generator', 'b2b tech reels', 'plg video marketing'],
    keywordsVi: ['video demo phần mềm', 'marketing saas tự động', 'giới thiệu ứng dụng công nghệ', 'tăng conversion landing page'],
  },

  {
    slug: 'e-commerce',
    nameEn: 'E-Commerce & Dropshipping',
    nameVi: 'Thương Mại Điện Tử & Dropshipping',
    category: 'E-Commerce & Retail',
    iconName: 'ShoppingBag',
    heroHeadlineEn: 'Viral Winning Product Ads That Drive Sub-$5 Customer Acquisition Costs',
    heroHeadlineVi: 'Video Quảng Cáo Sản Phẩm Viral Giúp Giảm Chi Phí Ra Đơn Dưới $5',
    heroSubheadlineEn: 'Scale your winning TikTok Shop, Shopee, and Shopify products with endless high-converting hooks and unboxing variations generated in minutes.',
    heroSubheadlineVi: 'Bứt phá doanh số TikTok Shop, Shopee và website với hàng chục biến thể mở đầu video và đập hộp thu hút được tạo chỉ trong vài phút.',
    painPoints: [
      {
        titleEn: 'Skyrocketing Paid Ad CPMs',
        titleVi: 'Giá Thầu Quảng Cáo Ngày Càng Tăng Cao',
        descEn: 'Rising ad costs mean you need high click-through rates and high conversion video creatives to stay profitable.',
        descVi: 'Giá CPM tăng cao buộc các nhà bán hàng phải có video với CTR và tỉ lệ chuyển đổi vượt trội mới giữ được lợi nhuận.',
      },
      {
        titleEn: 'Fast Creative Burnout on TikTok',
        titleVi: 'Quảng Cáo Nhanh Chóng Bị Chai Sau 3 Ngày',
        descEn: 'Winning ad creatives on TikTok exhaust their audience in 72 hours, forcing non-stop manual video production.',
        descVi: 'Một mẫu video win trên TikTok chỉ chạy tốt 3 ngày là bão hòa, bắt buộc phải liên tục có nội dung mới.',
      },
      {
        titleEn: 'Supplier Videos Lack Localization',
        titleVi: 'Video Của Xưởng Trung Quốc Không Phù Hợp Thị Trường',
        descEn: 'Repurposing factory videos with watermarks and foreign subtitles destroys buyer trust and gets flagged.',
        descVi: 'Lấy video của nhà cung cấp có logo lạ và chữ nước ngoài làm mất niềm tin của người mua và dễ bị đánh bản quyền.',
      },
    ],
    samplePromptTitleEn: 'Viral Gadget Problem-Solution TikTok Ad',
    samplePromptTitleVi: 'Kịch Bản Quảng Cáo Đồ Gia Dụng Thông Minh',
    samplePromptEn: 'Create a 15-second punchy product demo for an automatic mini vacuum cleaner. Hook: "Tell me your car seats look like this without telling me your car seats look like this." Fast cuts showing crumbs vanishing instantly.',
    samplePromptVi: 'Tạo video quảng cáo 15s cho máy hút bụi mini cầm tay trên ô tô. Hook: "Nhìn ghế xe thế này là biết chưa có máy này rồi!" Chuyển cảnh nhanh cảnh hút sạch vụn bánh trong 2 giây.',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2400,
      traditionalTurnaroundDays: 5,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 30,
      estimatedMonthlySavingsUsd: 2201,
      estimatedVideoOutputPerMonth: 120,
    },
    testimonial: {
      quoteEn: 'We generated $84,000 in revenue last month by testing 10 new Sophia video hooks every single morning.',
      quoteVi: 'Tháng vừa rồi shop chúng tôi đạt hơn 2 tỷ doanh thu nhờ thói quen test 10 mẫu hook video mới của Sophia mỗi buổi sáng.',
      author: 'Ryan Miller',
      roleEn: 'E-Commerce Founder',
      roleVi: 'Chủ Thương Hiệu Bán Lẻ',
      company: 'SwiftGear Direct',
      metrics: '$84,000 monthly revenue with 10 daily test hooks',
    },
    faqs: [
      {
        questionEn: 'Can I export videos in vertical 9:16 format with auto-caption styles?',
        questionVi: 'Sophia có xuất chuẩn khung hình dọc 9:16 với phụ đề động phong cách TikTok không?',
        answerEn: 'Yes! Sophia formats directly in 1080x1920 with high-contrast animated subtitles proven to boost watch time.',
        answerVi: 'Chắc chắn rồi! Video xuất ra đúng tỷ lệ 9:16 Full HD với chữ chạy động nhiều màu sắc bắt mắt tối ưu tỷ lệ xem hết clip.',
      },
    ],
    keywordsEn: ['ecommerce video ads', 'tiktok shop ad maker', 'dropshipping winning video', 'product demo ai'],
    keywordsVi: ['làm video bán hàng online', 'tạo video tiktok shop', 'chạy ads chuyển đổi', 'video đồ gia dụng thông minh'],
  },

  {
    slug: 'ai-automation',
    nameEn: 'AI Automation & Agencies',
    nameVi: 'Tự Động Hóa AI & Agency',
    category: 'Agency & Services',
    iconName: 'Cpu',
    heroHeadlineEn: 'Showcase Autonomous AI Workflows That Sign $5,000/Month Agency Retainers',
    heroHeadlineVi: 'Trình Diễn Giải Pháp Tự Động Hóa AI Chốt Hợp Đồng Agency $5.000/Tháng',
    heroSubheadlineEn: 'Demonstrate multi-agent orchestration, CRM automation, and custom LLM workflows with visual authority that proves high enterprise ROI.',
    heroSubheadlineVi: 'Chứng minh năng lực triển khai trợ lý ảo AI, tích hợp CRM tự động và mô hình ngôn ngữ lớn cho khách hàng doanh nghiệp.',
    painPoints: [
      {
        titleEn: 'Prospects Fail to Understand Abstract AI Services',
        titleVi: 'Khách Hàng Khó Hình Dung Dịch Vụ AI Vô Hình',
        descEn: 'Talking about LLMs and APIs sounds like techno-babble to business owners without visual workflow proof.',
        descVi: 'Khách hàng không hiểu API hay LLM là gì nếu không thấy màn hình tự động hóa vận hành thực tế.',
      },
      {
        titleEn: 'Competing Against Low-Priced Freelancers',
        titleVi: 'Bị Cạnh Tranh Phá Giá Bởi Các Freelancer Nghiệp Dư',
        descEn: 'Agencies need high-end architectural teardowns to position as elite enterprise partners rather than cheap bot builders.',
        descVi: 'Agency cần định vị là đối tác giải pháp doanh nghiệp cao cấp thay vì những người làm chatbot giá rẻ.',
      },
      {
        titleEn: 'High Cost of Building Bespoke Proof-of-Concepts',
        titleVi: 'Tốn Quá Nhiều Nguồn Lực Làm Bản Demo Cho Khách',
        descEn: 'Spending hours building custom client demos before winning contracts drains development bandwidth.',
        descVi: 'Mất cả tuần lập trình thử nghiệm trước khi khách đồng ý ký hợp đồng làm tốn kém chi phí nhân sự.',
      },
    ],
    samplePromptTitleEn: 'Multi-Agent Customer Support Automation Teardown',
    samplePromptTitleVi: 'Phân Tích Quy Trình Trợ Lý AI Chăm Sóc Khách Hàng 24/7',
    samplePromptEn: 'Create a 45-second agency pitch video demonstrating how an autonomous AI agent handles support tickets, updates Hubspot CRM, and issues refunds without human delay. Hook: "This company fired their $8K/month support agency and replaced it with a 3-agent pipeline."',
    samplePromptVi: 'Tạo video 45s giới thiệu quy trình trợ lý AI tự động trả lời khiếu nại, đồng bộ CRM và gửi hóa đơn trong 5 giây. Hook: "Doanh nghiệp này đã cắt giảm 80 triệu chi phí trực tổng đài mỗi tháng nhờ hệ thống 3 trợ lý AI hoạt động 24/7."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3600,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 3401,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'We closed 3 new agency retainer clients worth $14,500/month within two weeks of posting Sophia workflow teardowns on LinkedIn.',
      quoteVi: 'Chúng tôi ký thêm 3 khách hàng retainer trị giá hơn 300 triệu/tháng chỉ sau 2 tuần đăng tải video phân tích quy trình AI của Sophia lên LinkedIn.',
      author: 'Khang Pham',
      roleEn: 'Founder & AI Architect',
      roleVi: 'Sáng Lập Viên & Kiến Trúc Sư AI',
      company: 'OmniAI Solutions',
      metrics: '+$14,500/month recurring revenue closed',
    },
    faqs: [
      {
        questionEn: 'Can I white-label Sophia videos with our agency logo and branding?',
        questionVi: 'Tôi có thể gắn logo thương hiệu của Agency mình vào video không?',
        answerEn: 'Yes! Sophia allows custom intro/outro watermarks, color palettes, and branded intro stings.',
        answerVi: 'Được chứ! Bạn hoàn toàn có thể tùy chỉnh logo, bảng màu thương hiệu và phần mở đầu/kết thúc mang đậm bản sắc Agency của bạn.',
      },
    ],
    keywordsEn: ['ai agency marketing', 'automation video teardown', 'b2b ai workflow', 'enterprise ai pitch'],
    keywordsVi: ['marketing agency ai', 'giải pháp tự động hóa doanh nghiệp', 'dịch vụ chatbot b2b', 'tăng doanh thu agency'],
  },

  {
    slug: 'solopreneur',
    nameEn: 'Solopreneurs & Creators',
    nameVi: 'Kinh Doanh Độc Lập & Solopreneur',
    category: 'Creator Economy',
    iconName: 'Sparkle',
    heroHeadlineEn: 'Run A 7-Figure Faceless Content Empire As A One-Person Business',
    heroHeadlineVi: 'Vận Hành Đế Chế Video Triệu View Cho Doanh Nghiệp 1 Người',
    heroSubheadlineEn: 'Dominate TikTok, YouTube Shorts, and X without showing your face, hiring employees, or spending all day editing clips.',
    heroSubheadlineVi: 'Thống lĩnh các nền tảng video ngắn mà không cần lộ mặt, không cần thuê nhân viên và không phải ngồi hàng giờ cắt ghép.',
    painPoints: [
      {
        titleEn: 'Severe Solo Burnout',
        titleVi: 'Kiệt Sức Vì Phải Tự Làm Mọi Khâu Một Mình',
        descEn: 'Managing ideation, scriptwriting, voiceover, b-roll selection, editing, and publishing alone causes rapid burnout.',
        descVi: 'Một mình gánh vác từ lên ý tưởng, viết kịch bản, lồng tiếng, tìm tư liệu đến cắt ghép khiến bạn mệt mỏi.',
      },
      {
        titleEn: 'Reluctance to Show Face On-Camera',
        titleVi: 'Không Muốn Xuất Hiện Khuôn Mặt Trên Mạng Xã Hội',
        descEn: 'Many entrepreneurs want to monetize faceless content channels without sacrificing personal privacy.',
        descVi: 'Nhiều người muốn kiếm tiền từ kênh nội dung nhưng không muốn công khai danh tính và đời tư cá nhân.',
      },
      {
        titleEn: 'Inconsistent Content Schedules',
        titleVi: 'Không Duy Trì Được Lịch Đăng Đều Đặn',
        descEn: 'Skipping uploads for a few days ruins algorithmic momentum and stalls traffic growth.',
        descVi: 'Bỏ bê vài ngày không đăng video là thuật toán giảm đề xuất, mất trắng lượng traffic tích lũy.',
      },
    ],
    samplePromptTitleEn: 'Faceless $5K/Mo Business Model Breakdown',
    samplePromptTitleVi: 'Mô Hình Kiếm $5K/Tháng Cho Solopreneur Không Lộ Mặt',
    samplePromptEn: 'Generate a 45-second faceless video breakdown explaining how a solo creator sells $49 digital checklists via short video traffic. Hook: "If you want to build a $5K/month income stream in 2026 without showing your face or taking client calls, here is the roadmap."',
    samplePromptVi: 'Tạo video ngắn 45s chia sẻ cách 1 người xây dựng nguồn thu nhập thụ động từ sản phẩm số qua kênh video ngắn. Hook: "Nếu bạn muốn kiếm 100 triệu mỗi tháng mà không cần lộ mặt hay họp hành với khách, đây là lộ trình 3 bước."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 1500,
      traditionalTurnaroundDays: 5,
      sophiaMonthlyUsd: 99,
      sophiaTurnaroundSeconds: 30,
      estimatedMonthlySavingsUsd: 1401,
      estimatedVideoOutputPerMonth: 90,
    },
    testimonial: {
      quoteEn: 'I reached my first $5,000 MRR milestone in 45 days running two faceless channels completely powered by Sophia.',
      quoteVi: 'Tôi đạt cột mốc $5.000 MRR đầu tiên chỉ sau 45 ngày vận hành 2 kênh video không lộ mặt được tạo tự động bởi Sophia.',
      author: 'Minh Quan',
      roleEn: 'Solo Digital Entrepreneur',
      roleVi: 'Solopreneur & Nhà Sáng Tạo',
      company: 'Zenith Studio',
      metrics: 'First $5,000 MRR achieved in 45 days',
    },
    faqs: [
      {
        questionEn: 'How does the SOLO100 promo code work for solopreneurs?',
        questionVi: 'Mã ưu đãi SOLO100 áp dụng như thế nào cho người mới khởi nghiệp?',
        answerEn: 'Use code SOLO100 at checkout to receive an instant $100 discount off your Starter plan, bringing it down to just $99/month.',
        answerVi: 'Nhập mã SOLO100 khi đăng ký để được giảm ngay 2.500.000 VNĐ ($100), chỉ còn $99/tháng cho gói Starter.',
      },
    ],
    keywordsEn: ['faceless youtube channel ai', 'solopreneur video automation', 'passive income reels', 'solo creator tools'],
    keywordsVi: ['kênh tiktok không lộ mặt', 'kiếm tiền video ngắn ai', 'solopreneur tự động hóa', 'công cụ tạo video cho 1 người'],
  },

  {
    slug: 'dental',
    nameEn: 'Dental & Orthodontics',
    nameVi: 'Nha Khoa & Thẩm Mỹ Răng',
    category: 'Healthcare & Wellness',
    iconName: 'Smile',
    heroHeadlineEn: 'Radiant Smile Makeovers That Keep Dental Chairs Continuously Booked',
    heroHeadlineVi: 'Video Nụ Cười Rạng Rỡ Giúp Phòng Khám Nha Khoa Luôn Kín Lịch Hẹn',
    heroSubheadlineEn: 'Educate patients on clear aligners, porcelain veneers, and pain-free implant procedures with warm, anxiety-reducing visual video explainers.',
    heroSubheadlineVi: 'Tư vấn niềng răng trong suốt, bọc răng sứ và trồng răng Implant nhẹ nhàng, xóa tan nỗi sợ hãi đi nha khoa của khách hàng.',
    painPoints: [
      {
        titleEn: 'Patient Fear of Pain & Dental Anxiety',
        titleVi: 'Bệnh Nhân Sợ Đau & Lo Lắng Khi Đến Nha Khoa',
        descEn: 'Dental phobia stops thousands of patients from booking consultations unless addressed through calming video explanations.',
        descVi: 'Tâm lý sợ đau khiến nhiều người trì hoãn làm răng cho đến khi nhìn thấy quy trình nhẹ nhàng qua video.',
      },
      {
        titleEn: 'High Patient Acquisition Costs in Major Cities',
        titleVi: 'Chi Phí Chạy Quảng Cáo Ngành Nha Khoa Quá Cao',
        descEn: 'Bidding wars on Google Ads for dental implants exceed $50 per click, making organic social video crucial.',
        descVi: 'Giá click quảng cáo từ khóa nha khoa rất đắt đỏ, cần video mạng xã hội để thu hút khách tự nhiên.',
      },
      {
        titleEn: 'Price Resistance on High-Ticket Procedures',
        titleVi: 'Khách Đắn Đo Về Chi Phí Niềng Răng & Trồng Răng',
        descEn: 'Patients struggle to appreciate the value of high-tier orthodontics without clear visual simulation of long-term health benefits.',
        descVi: 'Khách hàng khó thấy hết giá trị nếu không được xem trực quan kết quả sau khi chỉnh nha.',
      },
    ],
    samplePromptTitleEn: 'Clear Aligner Smile Journey in 30 Seconds',
    samplePromptTitleVi: 'Hành Trình Niềng Răng Trong Suốt Trong 30s',
    samplePromptEn: 'Create a 30-second reassuring reel showcasing a 12-month clear aligner progression. Hook: "Think you are too old to fix your crooked teeth? Watch this 12-month transformation done without metal wires."',
    samplePromptVi: 'Tạo video ngắn 30s truyền cảm hứng về hành trình niềng răng trong suốt: Không đau, tự tin giao tiếp và sự thay đổi kỳ diệu của khuôn mặt. Hook: "Nhiều người nghĩ 30 tuổi là quá muộn để niềng răng, cho đến khi họ xem kết quả này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2500,
      traditionalTurnaroundDays: 10,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2301,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'We secured 22 new clear aligner cases in our first month using Sophia smile makeover explainers.',
      quoteVi: 'Nha khoa của chúng tôi nhận thêm 22 ca niềng răng trong suốt chỉ sau 1 tháng đăng tải các video giải đáp của Sophia.',
      author: 'Dr. Tuan Minh',
      roleEn: 'Chief Orthodontist',
      roleVi: 'Bác Sĩ Trưởng Khoa Chỉnh Nha',
      company: 'SmileArt Dental Clinic',
      metrics: '+22 high-ticket aligner cases booked',
    },
    faqs: [
      {
        questionEn: 'Can we add doctor introduction cards and booking hotline badges?',
        questionVi: 'Có thể chèn thông tin bằng cấp của bác sĩ và hotline phòng khám không?',
        answerEn: 'Yes! Sophia allows persistent doctor credentials, clinic certifications, and 1-tap booking prompts on all video templates.',
        answerVi: 'Có! Sophia hỗ trợ gắn huy hiệu chứng chỉ bác sĩ, địa chỉ cơ sở và nút gọi hotline đặt lịch khám.',
      },
    ],
    keywordsEn: ['dental clinic marketing', 'orthodontist reels', 'clear aligners video generator', 'dentist tiktok'],
    keywordsVi: ['marketing phòng khám nha khoa', 'video niềng răng trong suốt', 'quảng cáo trồng răng implant', 'tư vấn làm răng sứ'],
  },

  {
    slug: 'medical',
    nameEn: 'Medical & Healthcare Clinics',
    nameVi: 'Y Tế, Bác Sĩ & Phòng Khám',
    category: 'Healthcare & Wellness',
    iconName: 'Stethoscope',
    heroHeadlineEn: 'Trusted Health Guidance Videos That Connect Doctors With Patients Who Need Care',
    heroHeadlineVi: 'Video Y Khoa Đáng Tin Cậy Kết Nối Bác Sĩ Với Người Bệnh Cần Chăm Sóc',
    heroSubheadlineEn: 'Deliver empathetic, medically sound guidance on common symptoms, wellness prevention, and clinic services while building unshakeable patient trust.',
    heroSubheadlineVi: 'Truyền tải kiến thức phòng bệnh, nhận biết triệu chứng sớm và giới thiệu dịch vụ khám chữa bệnh với phong thái tận tâm, chuẩn mực y đức.',
    painPoints: [
      {
        titleEn: 'Rampant Medical Misinformation Online',
        titleVi: 'Nhiều Thông Tin Sức Khỏe Sai Lệch Trên Mạng',
        descEn: 'Patients follow dangerous internet myths; clinics need authoritative doctor-led videos to correct false advice.',
        descVi: 'Bệnh nhân dễ tin theo những mẹo chữa bệnh chưa kiểm chứng; cần bác sĩ lên tiếng qua video khoa học.',
      },
      {
        titleEn: 'Overwhelmed Consultation Desks',
        titleVi: 'Bàn Khám Bệnh Bị Quá Tải Câu Hỏi Lặp Lại',
        descEn: 'Doctors exhaust time repeating pre-procedure instructions that patients could digest via video before arriving.',
        descVi: 'Bác sĩ mất nhiều thời gian dặn dò kiêng khem trước phẫu thuật mà bệnh nhân có thể xem trước qua video.',
      },
      {
        titleEn: 'Strict Health Advertising Regulations',
        titleVi: 'Quy Định Quảng Cáo Y Tế Rất Khắt Khe',
        descEn: 'Healthcare ads get banned immediately unless framed strictly around accredited medical education.',
        descVi: 'Quảng cáo y tế dễ bị cấm nếu không được trình bày đúng chuẩn mực giáo dục sức khỏe cộng đồng.',
      },
    ],
    samplePromptTitleEn: '3 Warning Signs of Hormonal Imbalance',
    samplePromptTitleVi: '3 Dấu Hiệu Cảnh Báo Rối Loạn Nội Tiết Tố Sớm',
    samplePromptEn: 'Create a 45-second compassionate medical explainer outlining unexplained fatigue, sleep issues, and skin dryness as signs to check hormone levels. Hook: "If you feel exhausted despite sleeping 8 hours, your body is trying to warn you."',
    samplePromptVi: 'Tạo video y khoa 45s giải thích về tình trạng mệt mỏi kéo dài, rụng tóc và mất ngủ do rối loạn nội tiết. Hook: "Nếu bạn ngủ đủ 8 tiếng mà thức dậy vẫn kiệt sức, cơ thể bạn đang phát đi tín hiệu cầu cứu này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2800,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2601,
      estimatedVideoOutputPerMonth: 40,
    },
    testimonial: {
      quoteEn: 'Our clinic patient appointments doubled after launching weekly doctor health tips powered by Sophia.',
      quoteVi: 'Lượng bệnh nhân đặt lịch khám tại phòng khám chúng tôi tăng gấp đôi sau khi phát đều đặn các video tư vấn của bác sĩ.',
      author: 'Dr. Thao Nguyen',
      roleEn: 'Medical Director',
      roleVi: 'Giám Đốc Chuyên Môn',
      company: 'WellCare Health Center',
      metrics: '2x monthly appointment bookings',
    },
    faqs: [
      {
        questionEn: 'Can medical disclaimers be automatically embedded?',
        questionVi: 'Video có tự động đính kèm câu khuyến cáo y tế không?',
        answerEn: 'Yes, mandatory medical disclaimers ("Consult your physician for personalized diagnosis") are automatically attached.',
        answerVi: 'Có, các lưu ý y khoa bắt buộc ("Thông tin mang tính tham khảo, vui lòng khám trực tiếp") luôn được tự động hiển thị.',
      },
    ],
    keywordsEn: ['healthcare video marketing', 'doctor reels generator', 'medical clinic tiktok', 'patient education videos'],
    keywordsVi: ['marketing phòng khám y tế', 'bác sĩ tư vấn sức khỏe', 'video giáo dục y khoa', 'tìm bệnh nhân cho phòng khám'],
  },

  {
    slug: 'automotive',
    nameEn: 'Automotive & Dealerships',
    nameVi: 'Ô Tô & Xe Máy',
    category: 'High-Ticket Sales',
    iconName: 'Car',
    heroHeadlineEn: 'High-Octane Vehicle Walkthroughs That Bring Qualified Drivers To Your Showroom',
    heroHeadlineVi: 'Video Trải Nghiệm Xe Đỉnh Cao Kéo Khách Lái Thử Về Showroom',
    heroSubheadlineEn: 'Turn inventory stock listings into cinematic exhaust sound demos, interior tech reviews, and financing breakdowns that spark instant showroom visits.',
    heroSubheadlineVi: 'Biến kho xe sẵn có thành những video tiếng máy phấn khích, trải nghiệm tiện nghi nội thất và tư vấn trả góp rõ ràng giúp khách muốn lái thử ngay.',
    painPoints: [
      {
        titleEn: 'Depreciating Inventory Holding Costs',
        titleVi: 'Chi Phí Lãi Vay Tồn Kho Xe Cao',
        descEn: 'Every week a car sits on the lot bleeds capital and showroom lot fee overhead.',
        descVi: 'Mỗi chiếc xe nằm ở bãi quá lâu làm đọng vốn và tốn chi phí bảo quản.',
      },
      {
        titleEn: 'Buyers Research Extensively Online First',
        titleVi: 'Khách Hàng Nghiên Cứu Rất Kỹ Trên Mạng Trước Khi Đến',
        descEn: 'Car shoppers eliminate dealerships before ever calling unless they see transparent, high-definition video walkthroughs.',
        descVi: 'Người mua xe sẽ loại bỏ những showroom không có video quay thực tế chi tiết từng góc cạnh.',
      },
      {
        titleEn: 'Financing Confusion Deters Buyers',
        titleVi: 'Khách Ngại Thủ Tục Trả Góp Phức Tạp',
        descEn: 'Shoppers hesitate to inquire because they assume monthly payments are outside their current budget.',
        descVi: 'Khách phân vân không dám hỏi vì tưởng số tiền trả góp hàng tháng vượt quá khả năng tài chính.',
      },
    ],
    samplePromptTitleEn: 'Compact SUV Feature Walkthrough & Monthly Payment',
    samplePromptTitleVi: 'Review Mẫu SUV Đô Thị & Bài Toán Trả Góp Mỗi Tháng',
    samplePromptEn: 'Create a 35-second walkthrough of a popular compact SUV highlighting wireless Apple CarPlay, panoramic roof, and an estimated monthly finance payment breakdown. Hook: "Looking for an SUV under $25K with luxury features? Stop scrolling."',
    samplePromptVi: 'Tạo video 35s đánh giá mẫu SUV đô thị: Cửa sổ trời toàn cảnh, sạc không dây và bảng tính trả góp chỉ từ 7 triệu/tháng. Hook: "Nếu bạn đang tìm chiếc SUV gầm cao đi phố tiện nghi mà chỉ cần trả trước 150 triệu, đây là lựa chọn hàng đầu."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2700,
      traditionalTurnaroundDays: 7,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 45,
      estimatedMonthlySavingsUsd: 2501,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'We cleared 14 pre-owned vehicles in 3 weeks solely from TikTok walkthrough shorts created with Sophia.',
      quoteVi: 'Showroom chúng tôi bán được 14 xe đã qua sử dụng chỉ trong 3 tuần nhờ các video ngắn quay chi tiết xe do Sophia tạo ra.',
      author: 'Quoc Bao',
      roleEn: 'Sales Director',
      roleVi: 'Giám Đốc Bán Hàng',
      company: 'AutoStar Motors',
      metrics: '14 cars sold directly from social video leads',
    },
    faqs: [
      {
        questionEn: 'Can I generate videos directly from our car inventory URL?',
        questionVi: 'Tôi có thể dán link tin đăng xe để tạo video luôn không?',
        answerEn: 'Yes! Simply paste the listing page and Sophia extracts exterior photos, mileage, options, and price into a finished reel.',
        answerVi: 'Rất tiện lợi! Chỉ cần dán link trang bán xe, Sophia sẽ tự lấy ảnh, số km đã đi, trang bị và giá bán để xuất clip.',
      },
    ],
    keywordsEn: ['automotive video marketing', 'car dealership tiktok', 'vehicle walkthrough generator', 'car sales reels'],
    keywordsVi: ['marketing bán xe ô tô', 'video review xe hơi', 'tạo clip giới thiệu xe', 'quảng cáo showroom ô tô'],
  },

  {
    slug: 'financial-advisor',
    nameEn: 'Financial Advisory & Wealth',
    nameVi: 'Tư Vấn Tài Chính & Đầu Tư',
    category: 'Financial Services',
    iconName: 'TrendingUp',
    heroHeadlineEn: 'Clarity-Driven Wealth Preservation Advice That High-Net-Worth Investors Value',
    heroHeadlineVi: 'Video Quản Lý Gia Sản & Đầu Tư Được Giới Thượng Lưu Đánh Giá Cao',
    heroSubheadlineEn: 'Break down inflation hedges, asset allocation strategies, and retirement tax planning into visually elegant insights that attract accredited investors.',
    heroSubheadlineVi: 'Phân tích chiến lược phòng ngừa lạm phát, phân bổ tài sản và kế hoạch tài chính hưu trí với góc nhìn sắc bén, thu hút các nhà đầu tư lớn.',
    painPoints: [
      {
        titleEn: 'Difficulty Reaching High-Net-Worth Prospects',
        titleVi: 'Khó Tiếp Cận Khách Hàng Có Tài Sản Lớn (HNWI)',
        descEn: 'High-income earners ignore generic banner ads; they only engage with sharp, credible macroeconomic commentary.',
        descVi: 'Người có tiền không bấm vào quảng cáo đại trà; họ chỉ lắng nghe những chuyên gia có góc nhìn sâu sắc.',
      },
      {
        titleEn: 'Volatile Markets Create Client Panic',
        titleVi: 'Thị Trường Biến Động Khiến Nhà Đầu Tư Hoang Mang',
        descEn: 'Advisors lose clients to panic selling when they lack the speed to publish calm, rational market update videos.',
        descVi: 'Nhà đầu tư dễ bán tháo theo cảm xúc nếu chuyên gia không kịp thời có video phân tích bình ổn tâm lý.',
      },
      {
        titleEn: 'Strict Financial Compliance Rules',
        titleVi: 'Rào Cản Pháp Lý Trong Tư Vấn Đầu Tư',
        descEn: 'Advisors cannot make guaranteed return promises; educational storytelling is the only compliant growth channel.',
        descVi: 'Không được cam kết lợi nhuận; chia sẻ kiến thức quản trị rủi ro là con đường thu hút khách hợp pháp duy nhất.',
      },
    ],
    samplePromptTitleEn: 'Asset Allocation When Inflation Stays Stubborn',
    samplePromptTitleVi: 'Chiến Lược Phân Bổ Tài Sản Khi Lạm Phát Kéo Dài',
    samplePromptEn: 'Create a 45-second high-finance breakdown comparing cash drag vs diversified dividend portfolios during high-rate regimes. Hook: "Holding cash in 2026 feels safe, but here is how the silent tax of inflation is eroding your purchasing power."',
    samplePromptVi: 'Tạo video tài chính 45s phân tích thiệt hại khi để tiền mặt quá nhiều so với danh mục cổ tức và bất động sản dòng tiền. Hook: "Giữ tiền mặt tạo cảm giác an toàn, nhưng đây là cách lạm phát đang âm thầm bào mòn tài sản của bạn."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3200,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 3001,
      estimatedVideoOutputPerMonth: 40,
    },
    testimonial: {
      quoteEn: 'I onboarded $4.2M in new advisory assets under management directly from viewers of my Sophia educational shorts.',
      quoteVi: 'Tôi đã tiếp nhận quản lý thêm hơn 100 tỷ đồng vốn ủy thác từ những thân chủ theo dõi chuỗi video kiến thức tài chính của tôi.',
      author: 'Derrick Lam',
      roleEn: 'Wealth Manager',
      roleVi: 'Chuyên Gia Quản Lý Gia Sản',
      company: 'Heritage Capital Advisory',
      metrics: '$4.2M in new AUM onboarded',
    },
    faqs: [
      {
        questionEn: 'Can Sophia integrate real-time financial charts and data graphics?',
        questionVi: 'Sophia có hỗ trợ chèn biểu đồ tài chính và số liệu trực quan không?',
        answerEn: 'Yes, Sophia includes modern animated line graphs, pie charts, and asset comparison visuals.',
        answerVi: 'Có, Sophia tích hợp sẵn các mẫu biểu đồ động, đồ thị cột và bảng so sánh danh mục trực quan.',
      },
    ],
    keywordsEn: ['financial advisor marketing', 'wealth management reels', 'finance video generator', 'investor lead gen'],
    keywordsVi: ['marketing tư vấn tài chính', 'video quản lý gia sản', 'kiến thức đầu tư chứng khoán', 'tìm khách hàng đầu tư'],
  },

  {
    slug: 'travel',
    nameEn: 'Travel & Hospitality',
    nameVi: 'Du Lịch & Khách Sạn',
    category: 'Local Hospitality',
    iconName: 'Plane',
    heroHeadlineEn: 'Wanderlust-Inducing Travel Itineraries That Book Out Tours & Rooms',
    heroHeadlineVi: 'Video Trải Nghiệm Du Lịch Đẹp Như Mơ Giúp Tour & Phòng Luôn Kín Chỗ',
    heroSubheadlineEn: 'Produce breathtaking resort tours, secret local itinerary guides, and flight deal announcements that trigger immediate vacation bookings.',
    heroSubheadlineVi: 'Xuất những video khám phá resort thơ mộng, cẩm nang du lịch bản địa và tour trọn gói hấp dẫn thôi thúc du khách xách balo lên và đi.',
    painPoints: [
      {
        titleEn: 'High OTA Commission Fees',
        titleVi: 'Phí Hoa Hồng Của Các Sàn OTA Quá Cao',
        descEn: 'Hotels lose 15% - 25% of every reservation to booking platforms; direct booking video funnels preserve margins.',
        descVi: 'Khách sạn phải trả 15% - 25% cho Agoda/Booking; video mạng xã hội giúp kéo khách đặt phòng trực tiếp để tăng lợi nhuận.',
      },
      {
        titleEn: 'Off-Season Occupancy Slumps',
        titleVi: 'Tỉ Lệ Trống Phòng Vào Mùa Thấp Điểm',
        descEn: 'Resorts bleed profits during rainy months without localized weekend getaway promotions.',
        descVi: 'Resort vắng khách mùa thấp điểm nếu không có các gói combo nghỉ dưỡng cuối tuần hấp dẫn.',
      },
      {
        titleEn: 'Static Destination Photos Look Ordinary',
        titleVi: 'Ảnh Chụp Tĩnh Không Thể Hiện Hết Vẻ Đẹp Điểm Đến',
        descEn: 'Static travel brochures fail to capture the breeze, turquoise water, and sunset ambiance that motivate trips.',
        descVi: 'Ảnh chụp đơn thuần không diễn tả được làn nước trong xanh, tiếng sóng biển và không khí nghỉ dưỡng đích thực.',
      },
    ],
    samplePromptTitleEn: '3-Day Secret Island Getaway Itinerary',
    samplePromptTitleVi: 'Lịch Trình 3 Ngày 2 Đêm Khám Phá Hòn Đảo Bí Mật',
    samplePromptEn: 'Create a 30-second dreamlike travel reel highlighting a quiet island escape: ocean-view villa waking up, fresh seafood barbecue at sunset, and coral diving. Hook: "If you need an escape from the city this weekend, save this itinerary immediately."',
    samplePromptVi: 'Tạo video ngắn 30s tràn đầy năng lượng: Biệt thự view biển đón bình minh, lặn ngắm san hô và tiệc nướng hải sản bên bờ biển. Hook: "Nếu bạn đang quá mệt mỏi với khói bụi thành phố, lưu ngay lịch trình nghỉ ngơi cuối tuần này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2600,
      traditionalTurnaroundDays: 10,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 45,
      estimatedMonthlySavingsUsd: 2401,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'Direct website bookings jumped by 62%, saving us over $8,000 in monthly OTA commissions.',
      quoteVi: 'Lượng khách đặt phòng trực tiếp qua fanpage tăng 62%, giúp khu nghỉ dưỡng tiết kiệm gần 200 triệu tiền phí sàn mỗi tháng.',
      author: 'Mai Linh',
      roleEn: 'Marketing Director',
      roleVi: 'Giám Đốc Tiếp Thị',
      company: 'Aura Eco-Resort & Spa',
      metrics: '+62% direct bookings, $8,000 OTA fees saved',
    },
    faqs: [
      {
        questionEn: 'Can we dynamically update seasonal pricing packages in videos?',
        questionVi: 'Có thể thay đổi giá gói combo theo từng mùa không?',
        answerEn: 'Yes, modify the pricing text in your prompt and re-generate the entire video in under 60 seconds.',
        answerVi: 'Rất dễ dàng, chỉ cần sửa số tiền trong câu lệnh và bấm xuất lại video mới chỉ trong chưa đầy 60 giây.',
      },
    ],
    keywordsEn: ['travel marketing video', 'resort reels generator', 'tour operator tiktok', 'vacation booking ai'],
    keywordsVi: ['marketing du lịch khách sạn', 'làm video giới thiệu tour', 'review resort nghỉ dưỡng', 'clip du lịch tiktok'],
  },

  {
    slug: 'home-services',
    nameEn: 'Home Services & Cleaning',
    nameVi: 'Dịch Vụ Nhà Cửa & Vệ Sinh',
    category: 'Local Hospitality',
    iconName: 'Home',
    heroHeadlineEn: 'Satisfying Deep-Clean & Renovation Videos That Keep Local Technicians Fully Dispatched',
    heroHeadlineVi: 'Video Vệ Sinh Nhà Cửa Thỏa Mãn Mắt Nhìn Giúp Đội Thợ Luôn Kín Lịch',
    heroSubheadlineEn: 'Leverage the viral phenomenon of oddly satisfying cleaning transformations, pest elimination, and HVAC repairs to dominate local residential service calls.',
    heroSubheadlineVi: 'Tận dụng sức hút kỳ diệu của những video dọn dẹp trước/sau siêu sạch để thu hút cư dân trong khu vực gọi dịch vụ sửa chữa và vệ sinh nhà cửa.',
    painPoints: [
      {
        titleEn: 'Competing on Low Price with Unvetted Freelancers',
        titleVi: 'Bị Cạnh Tranh Giá Rẻ Bởi Thợ Nghiệp Dư',
        descEn: 'Professional companies lose jobs to cheap handymen unless they showcase superior equipment and safety rigor.',
        descVi: 'Khách dễ chọn thợ tự do giá rẻ nếu không thấy được sự chuyên nghiệp, máy móc hiện đại của công ty bạn.',
      },
      {
        titleEn: 'Unpredictable Local Lead Flow',
        titleVi: 'Lượng Khách Gọi Lúc Nhiều Lúc Ít Thất Thường',
        descEn: 'Service crews sit idle on slow weeks when offline flyers and word-of-mouth dry up.',
        descVi: 'Đội ngũ thợ phải ngồi chờ việc vào những tuần vắng khách do tiếp thị truyền thống không hiệu quả.',
      },
      {
        titleEn: 'High Google Local Service Ad Costs',
        titleVi: 'Chi Phí Chạy Quảng Cáo Tìm Thợ Quá Đắt',
        descEn: 'Plumbing and HVAC search keywords cost upwards of $40 per click on Google Ads.',
        descVi: 'Giá đấu thầu từ khóa sửa điện nước, bảo dưỡng điều hòa trên Google rất cao.',
      },
    ],
    samplePromptTitleEn: 'Satisfying Deep Rug Wash Transformation',
    samplePromptTitleVi: 'Biến Hình Giặt Thảm Siêu Sạch Thỏa Mãn Mắt Nhìn',
    samplePromptEn: 'Create a 25-second satisfying cleaning reel showing heavily stained sofa steam extraction, high-pressure foam, and crystal clean result. Hook: "Watch this 5-year-old sofa get brought back to life in 25 seconds."',
    samplePromptVi: 'Tạo video ngắn 25s quay cảnh giặt thảm và ghế sofa bằng máy hút hơi nước nóng: Bọt bẩn được hút sạch bóng trả lại màu sắc như mới. Hook: "Chiếc ghế sofa 5 năm chưa giặt này sẽ khiến bạn ngỡ ngàng sau 25 giây."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 1900,
      traditionalTurnaroundDays: 7,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 45,
      estimatedMonthlySavingsUsd: 1701,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'Our dispatch calendar filled up 2 weeks in advance within 10 days of posting localized deep cleaning reels.',
      quoteVi: 'Lịch làm việc của đội thợ vệ sinh chúng tôi kín chỗ trước 2 tuần chỉ sau 10 ngày đăng các clip giặt đệm/sofa lên mạng xã hội.',
      author: 'Anh Tuan',
      roleEn: 'Operations Manager',
      roleVi: 'Trưởng Phòng Vận Hành',
      company: 'EcoClean Pro Services',
      metrics: 'Schedule booked 2 weeks out in advance',
    },
    faqs: [
      {
        questionEn: 'Can Sophia focus videos on specific postal codes or service districts?',
        questionVi: 'Tôi có thể hướng nội dung đến đúng quận/huyện mình phục vụ không?',
        answerEn: 'Yes, include your target neighborhoods and city names in the script prompt to capture local search relevance.',
        answerVi: 'Được chứ, chỉ cần điền tên quận/huyện vào kịch bản, Sophia sẽ chèn lời nhắc phục vụ tận nơi trong khu vực.',
      },
    ],
    keywordsEn: ['home services marketing', 'cleaning business reels', 'plumbing video generator', 'local service ads'],
    keywordsVi: ['marketing dịch vụ vệ sinh', 'video giặt nệm sofa', 'tìm khách sửa chữa nhà', 'quảng cáo dịch vụ gia đình'],
  },

  {
    slug: 'wedding',
    nameEn: 'Wedding & Event Planning',
    nameVi: 'Cưới Hỏi & Chụp Ảnh Cưới',
    category: 'Local Hospitality',
    iconName: 'Heart',
    heroHeadlineEn: 'Enchanting Wedding Highlights That Make Brides Book Their Dream Date Immediately',
    heroHeadlineVi: 'Khoảnh Khắc Cưới Đẹp Như Cổ Tích Khiến Cô Dâu Đặt Lịch Ngay Tức Khắc',
    heroSubheadlineEn: 'Showcase emotional vows, magical floral decorations, and fairy-tale celebrations with cinematic music and storytelling that tugs at heartstrings.',
    heroSubheadlineVi: 'Trình diễn những lời thề nguyện xúc động, không gian tiệc cưới lộng lẫy và khoảnh khắc thiêng liêng với âm nhạc điện ảnh lay động lòng người.',
    painPoints: [
      {
        titleEn: 'Long Hesitation Period Before Booking',
        titleVi: 'Khách Hàng Cân Nhắc Quá Lâu Trước Khi Đặt Cọc',
        descEn: 'Couples tour dozens of vendors; agencies need emotionally gripping highlight reels to close the deal.',
        descVi: 'Các cặp đôi tham khảo nhiều nơi; bạn cần video cảm xúc chạm đến trái tim để họ quyết định chọn bạn.',
      },
      {
        titleEn: 'High Production Effort for Teaser Clips',
        titleVi: 'Mất Quá Nhiều Công Sức Làm Clip Teaser Mẫu',
        descEn: 'Video editors spend days cutting wedding trailers when couples demand immediate social previews.',
        descVi: 'Thợ dựng mất cả tuần cắt ghép trong khi cô dâu chú rể muốn có clip ngắn đăng TikTok ngay hôm sau.',
      },
      {
        titleEn: 'Seasonality Feast or Famine',
        titleVi: 'Doanh Thu Phụ Thuộc Vào Mùa Cưới',
        descEn: 'Planners experience quiet spring months unless they keep a steady flow of bridal inspiration reels circulating.',
        descVi: 'Mùa vắng đám cưới dễ hụt dòng tiền nếu không liên tục duy trì hình ảnh thương hiệu để nhận đặt cọc trước.',
      },
    ],
    samplePromptTitleEn: 'Emotional First Look & Outdoor Vow Teaser',
    samplePromptTitleVi: 'Khoảnh Khắc First Look & Trao Lời Thề Nguyện Xúc Động',
    samplePromptEn: 'Create a 30-second romantic wedding trailer focusing on the groom seeing his bride in her gown for the first time, tearful vows under fairy lights, and an enthusiastic confetti exit. Hook: "Warning: Have tissues ready before watching this entrance."',
    samplePromptVi: 'Tạo video ngắn 30s ngọt ngào: Ánh mắt chú rể lần đầu ngắm cô dâu trong váy cưới lộng lẫy, giọt nước mắt hạnh phúc và pháo hoa rực rỡ. Hook: "Hãy chuẩn bị khăn giấy trước khi xem khoảnh khắc thiêng liêng này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2800,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2601,
      estimatedVideoOutputPerMonth: 50,
    },
    testimonial: {
      quoteEn: 'Brides mention our emotional Sophia-edited TikTok trailers in almost every initial inquiry message.',
      quoteVi: 'Hầu như cô dâu nào nhắn tin cho studio cũng nhắc đến những đoạn video ngắn xúc động mà chúng tôi đăng trên TikTok.',
      author: 'Lan Phuong',
      roleEn: 'Lead Wedding Planner',
      roleVi: 'Chuyên Gia Tổ Chức Tiệc Cưới',
      company: 'EverAfter Bridal Studio',
      metrics: '+45% deposit booking rate from initial tours',
    },
    faqs: [
      {
        questionEn: 'Can we pair royalty-free cinematic music with emotional wedding scenes?',
        questionVi: 'Sophia có kho nhạc nền điện ảnh không lo dính bản quyền không?',
        answerEn: 'Yes, Sophia pairs every generated video with 100% commercially licensed soundtrack options safe for social platforms.',
        answerVi: 'Có, toàn bộ nhạc nền của Sophia đều có bản quyền thương mại đầy đủ, không lo bị tắt tiếng trên TikTok/Facebook.',
      },
    ],
    keywordsEn: ['wedding video marketing', 'bridal reels generator', 'wedding planner tiktok', 'wedding highlights ai'],
    keywordsVi: ['làm video phóng sự cưới', 'quay phim chụp ảnh cưới', 'quảng cáo tiệc cưới', 'clip đám cưới triệu view'],
  },

  {
    slug: 'logistics',
    nameEn: 'Logistics & Freight',
    nameVi: 'Vận Tải & Kho Vận',
    category: 'Technology',
    iconName: 'Truck',
    heroHeadlineEn: 'Reliable Supply Chain & Fleet Explainers That Win Commercial Shipping Contracts',
    heroHeadlineVi: 'Video Giải Pháp Vận Tải & Kho Bãi Chuyên Nghiệp Ký Hợp Đồng B2B',
    heroSubheadlineEn: 'Demonstrate cold-chain security, automated warehouse sorting, and cross-border customs speed to win manufacturer and e-commerce logistics tenders.',
    heroSubheadlineVi: 'Trình diễn năng lực kho bãi tự động, hệ thống xe tải hiện đại và tốc độ thông quan hải quan giúp thuyết phục các chủ hàng lớn.',
    painPoints: [
      {
        titleEn: 'Commoditized Price Slashing by Competitors',
        titleVi: 'Cạnh Tranh Phá Giá Cước Vận Chuyển',
        descEn: 'Logistics firms struggle against cut-rate operators unless they clearly prove reliability, tracking, and cargo safety.',
        descVi: 'Chủ hàng dễ so bì từng đồng cước phí nếu bạn không chứng minh được độ an toàn và uy tín qua video.',
      },
      {
        titleEn: 'Complex B2B Tendering Cycles',
        titleVi: 'Hồ Sơ Năng Lực Dày Cộp Khó Đọc',
        descEn: 'Procurement teams skip dense 80-page PDF capability decks; a concise 60-second video wins executive attention.',
        descVi: 'Bộ phận mua hàng doanh nghiệp ngại đọc hồ sơ PDF dày cộp; video 60s tóm tắt năng lực mang lại hiệu quả vượt trội.',
      },
      {
        titleEn: 'Driver & Warehouse Staff Recruitment Shortages',
        titleVi: 'Khó Khăn Tuyển Dụng Tài Xế & Nhân Sự Kho',
        descEn: 'Attracting reliable commercial drivers requires modern, respectable brand video storytelling.',
        descVi: 'Muốn tuyển đội ngũ tài xế tận tâm cần hình ảnh doanh nghiệp đàng hoàng, minh bạch chế độ đãi ngộ.',
      },
    ],
    samplePromptTitleEn: 'Cold Chain Pharmaceutical Logistics Integrity',
    samplePromptTitleVi: 'Quy Trình Vận Chuyển Hàng Lạnh Dược Phẩm Đạt Chuẩn',
    samplePromptEn: 'Create a 40-second authoritative supply chain breakdown highlighting continuous IoT temperature telemetry, expedited customs clearance, and zero-breakage guarantee. Hook: "When a 1-degree temperature spike destroys a $200K cargo shipment, who do you trust?"',
    samplePromptVi: 'Tạo video năng lực vận tải 40s: Hệ thống giám sát nhiệt độ xe lạnh 24/7, định vị GPS chuẩn xác và cam kết đền bù 100%. Hook: "Khi chỉ lệch 1 độ C có thể làm hỏng lô hàng bạc tỷ, doanh nghiệp của bạn đang tin tưởng ai?"',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3100,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2901,
      estimatedVideoOutputPerMonth: 40,
    },
    testimonial: {
      quoteEn: 'A short Sophia capability video shared during an enterprise RFP helped us win a $180,000 annual distribution contract.',
      quoteVi: 'Video giới thiệu năng lực kho bãi gửi kèm hồ sơ thầu đã giúp chúng tôi trúng gói vận chuyển trị giá 4 tỷ đồng/năm.',
      author: 'Hoang Nam',
      roleEn: 'Commercial Director',
      roleVi: 'Giám Đốc Thương Mại',
      company: 'TransPacific Global Logistics',
      metrics: 'Won $180K annual enterprise shipping RFP',
    },
    faqs: [
      {
        questionEn: 'Can Sophia render 3D warehouse and fleet graphics?',
        questionVi: 'Sophia có hỗ trợ minh họa đồ họa kho hàng và đội xe tải không?',
        answerEn: 'Yes! Sophia integrates clean industrial isometric diagrams and route simulation graphics.',
        answerVi: 'Có! Sophia cung cấp các mẫu đồ họa mô phỏng sơ đồ tuyến đường, cảng biển và quy trình kho hàng rất chuyên nghiệp.',
      },
    ],
    keywordsEn: ['logistics video marketing', 'freight forwarder reels', 'supply chain video generator', 'b2b shipping ads'],
    keywordsVi: ['marketing logistics vận tải', 'hồ sơ năng lực công ty vận chuyển', 'giới thiệu kho bãi b2b', 'dịch vụ xuất nhập khẩu'],
  },

  {
    slug: 'construction',
    nameEn: 'Construction & Architecture',
    nameVi: 'Xây Dựng & Kiến Trúc',
    category: 'High-Ticket Sales',
    iconName: 'Hammer',
    heroHeadlineEn: 'Stunning Blueprint-To-Reality Time-Lapses That Land High-Ticket Building Contracts',
    heroHeadlineVi: 'Video Quá Trình Thi Công Từ Bản Vẽ Đến Thực Tế Giúp Ký Hợp Đồng Tiền Tỷ',
    heroSubheadlineEn: 'Turn structural blueprints, 3D renderings, and site progress photos into breathtaking building transformation videos that prove craftsmanship.',
    heroSubheadlineVi: 'Biến bản vẽ thiết kế 3D và hình ảnh công trường thành những video lột xác công trình ấn tượng, khẳng định uy tín và chất lượng thi công.',
    painPoints: [
      {
        titleEn: 'Homeowners Fear Subcontractor Delays & Budget Overruns',
        titleVi: 'Chủ Nhà Sợ Bị Đội Vốn & Chậm Tiến Độ',
        descEn: 'Clients hesitate to sign large building contracts without seeing transparent proof of on-time project execution.',
        descVi: 'Khách xây nhà rất lo lắng nhà thầu làm ẩu, kéo dài thời gian và phát sinh chi phí.',
      },
      {
        titleEn: 'Hard to Show Value in Unfinished Concrete',
        titleVi: 'Khó Cho Khách Thấy Nét Đẹp Khi Công Trình Chưa Xong',
        descEn: 'Showing raw rebar and concrete confuses clients unless bridged with 3D architectural vision overlays.',
        descVi: 'Hình ảnh công trường thô ráp không gây ấn tượng nếu không được lồng ghép với bản vẽ phối cảnh hoàn thiện.',
      },
      {
        titleEn: 'Long Sales Cycles for Multi-Billion VND Contracts',
        titleVi: 'Thời Gian Thương Thảo Hợp Đồng Kéo Dài Hàng Tháng',
        descEn: 'High-ticket residential and commercial projects require continuous brand authority to beat rival contractors.',
        descVi: 'Những hợp đồng xây dựng tiền tỷ đòi hỏi nhà thầu phải liên tục thể hiện năng lực để vượt qua đối thủ.',
      },
    ],
    samplePromptTitleEn: 'Modern Villa Foundation-to-Finish Time-Lapse',
    samplePromptTitleVi: 'Hành Trình Thi Công Biệt Thự Hiện Đại Từ Móng Đến Hoàn Thiện',
    samplePromptEn: 'Create a 40-second dynamic progress reel of a 3-story modern villa: foundation pouring, steel framing, interior joinery, and the final night-lit reveal. Hook: "Building your dream home should not be a nightmare. Here is how we delivered 350m2 in 120 days."',
    samplePromptVi: 'Tạo video 40s hành trình xây dựng biệt thự vườn 3 tầng: Đổ móng vững chắc, cất nóc, hoàn thiện nội thất và bàn giao chìa khóa trao tay. Hook: "Xây nhà không hề là cơn ác mộng nếu bạn chọn đúng nhà thầu tận tâm. Xem cách chúng tôi hoàn thiện 350m2 trong 120 ngày."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 3400,
      traditionalTurnaroundDays: 14,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 3201,
      estimatedVideoOutputPerMonth: 40,
    },
    testimonial: {
      quoteEn: 'A homeowner saw our villa progress reel on Facebook and signed an 8.5 billion VND design & build turnkey contract.',
      quoteVi: 'Một gia chủ tình cờ xem được video thi công biệt thự của chúng tôi trên Facebook và đã tin tưởng ký hợp đồng trọn gói 8,5 tỷ đồng.',
      author: 'Kts. Duc Thang',
      roleEn: 'Principal Architect & Contractor',
      roleVi: 'Kiến Trúc Sư Trưởng',
      company: 'Thang Long Design Build',
      metrics: '8.5B VND residential build contract signed',
    },
    faqs: [
      {
        questionEn: 'Can we create videos using our architectural 3D Sketchup/Lumion renders?',
        questionVi: 'Tôi có thể tải ảnh phối cảnh 3D từ Lumion hoặc SketchUp lên không?',
        answerEn: 'Yes! Sophia adds camera sweeps, animated lighting, and background ambiance to breathe life into still 3D renders.',
        answerVi: 'Rất tuyệt vời! Sophia tự động tạo góc quay lướt điện ảnh, hiệu ứng ánh sáng ngày/đêm sống động cho các ảnh phối cảnh 3D tĩnh.',
      },
    ],
    keywordsEn: ['construction marketing video', 'architecture reels generator', 'home builder tiktok', 'construction lead gen'],
    keywordsVi: ['marketing công ty xây dựng', 'video thiết kế kiến trúc', 'clip thi công nhà trọn gói', 'tìm khách xây nhà biệt thự'],
  },

  {
    slug: 'pets',
    nameEn: 'Pets & Veterinary',
    nameVi: 'Thú Cưng & Thú Y',
    category: 'Healthcare & Wellness',
    iconName: 'PawPrint',
    heroHeadlineEn: 'Heartwarming Pet Care & Grooming Transformations That Win Devoted Fur Parents',
    heroHeadlineVi: 'Video Chăm Sóc & Spa Thú Cưng Đáng Yêu Khiến Hội Yêu Chó Mèo Mê Mẩn',
    heroSubheadlineEn: 'Produce viral pet grooming reveals, vet wellness advice, and playful adoption reels that establish your clinic as the friendliest neighborhood haven.',
    heroSubheadlineVi: 'Xuất những video cắt tỉa lông chó mèo biến hình ngoạn mục, lời khuyên chăm sóc thú cưng từ bác sĩ thú y giúp phòng khám luôn đông khách.',
    painPoints: [
      {
        titleEn: 'Pet Parents Anxious About Rough Handling',
        titleVi: 'Chủ Nuôi Lo Lắng Thú Cưng Bị Đau Hoặc Sợ Hãi',
        descEn: 'Pet owners hesitate to try new groomers or vets unless they see gentle, fear-free handling via video.',
        descVi: 'Chủ chó mèo rất sợ giao thú cưng cho nơi làm ẩu; video tận tâm vuốt ve sẽ tạo dựng lòng tin tuyệt đối.',
      },
      {
        titleEn: 'High Competition Among Neighborhood Pet Stores',
        titleVi: 'Cạnh Tranh Gay Gắt Giữa Các Pet Shop Trong Khu Vực',
        descEn: 'Pet shops struggle to differentiate on pet food alone without offering high-margin grooming packages.',
        descVi: 'Bán thức ăn thú cưng lợi nhuận mỏng; cần các gói dịch vụ spa/tỉa lông để gia tăng lợi nhuận.',
      },
      {
        titleEn: 'Emergency Care Inquiries Happen Fast Online',
        titleVi: 'Khách Cần Tư Vấn Cấp Cứu Nhanh Chóng',
        descEn: 'Owners urgently search social media when their pets show acute distress or unusual behavior.',
        descVi: 'Khi thú cưng bỏ ăn hay nôn mửa, chủ nuôi thường tìm kiếm video triệu chứng để đưa đi viện kịp thời.',
      },
    ],
    samplePromptTitleEn: 'Matted Poodle Glow-Up Grooming Transformation',
    samplePromptTitleVi: 'Màn Lột Xác Spa Cắt Tỉa Lông Cho Bé Cún Poodle',
    samplePromptEn: 'Create a 25-second heartwarming grooming reel: gentle shampoo lather, scissor scissoring around the face, and the adorable happy tail wag finish. Hook: "From walking mop to runway superstar in 25 seconds."',
    samplePromptVi: 'Tạo video 25s đáng yêu: Tắm bọt êm ái cho bé cún, cắt tỉa tròn xoe khuôn mặt như gấu bông và cái vẫy đuôi mừng rỡ. Hook: "Từ một cục bông rối xù biến thành siêu mẫu 4 chân chỉ sau buổi spa này."',
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 1800,
      traditionalTurnaroundDays: 5,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 40,
      estimatedMonthlySavingsUsd: 1601,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: 'Our pet salon grooming bookings doubled in 3 weeks after our grooming transformation reels went viral locally.',
      quoteVi: 'Lịch spa thú cưng của tiệm chúng tôi kín từ sáng đến tối sau khi chuỗi video cắt tỉa biến hình cún cưng lên xu hướng địa phương.',
      author: 'Ngoc Anh',
      roleEn: 'Founder & Head Groomer',
      roleVi: 'Chủ Spa Thú Cưng',
      company: 'PawParadise Grooming Lounge',
      metrics: '2x grooming bookings in 3 weeks',
    },
    faqs: [
      {
        questionEn: 'Can we add appointment booking links directly to our veterinary Telegram or WhatsApp?',
        questionVi: 'Có thể gắn link đặt lịch khám thú y qua Telegram hay Zalo không?',
        answerEn: 'Yes! Sophia integrates 1-click booking deep links so pet owners can schedule appointments in seconds.',
        answerVi: 'Được chứ! Sophia hỗ trợ gắn link điều hướng trực tiếp sang Zalo hoặc Telegram để khách gửi ảnh tình trạng thú cưng và đặt lịch.',
      },
    ],
    keywordsEn: ['pet marketing video', 'dog grooming reels', 'vet clinic tiktok', 'pet shop video generator'],
    keywordsVi: ['marketing spa thú cưng', 'video cắt tỉa lông chó mèo', 'phòng khám thú y tiktok', 'chăm sóc thú cưng tự động'],
  },
];

/** Mapping aliases to canonical slugs for seamless navigation */
export const SOLUTION_ALIASES: Record<string, string> = {
  beauty: 'cosmetics',
  restaurant: 'f-and-b',
  education: 'courses',
  legal: 'lawyer',
  health: 'medical',
  crypto: 'financial-advisor',
  accounting: 'lawyer',
  cleaning: 'home-services',
  spa: 'cosmetics',
  barber: 'cosmetics',
};

/** Get canonical list of primary solution slugs */
export function getAllSolutionSlugs(): string[] {
  return PRIMARY_SOLUTIONS.map((s) => s.slug);
}

/**
 * Find solution industry profile by slug or alias.
 * If slug belongs to the broader 52-niche catalog (`NICHE_LABELS`),
 * a high-quality deterministic fallback profile is generated automatically.
 */
export function getSolutionIndustry(slugOrAlias: string): SolutionIndustry {
  const normalized = slugOrAlias.toLowerCase().trim();
  const canonicalSlug = SOLUTION_ALIASES[normalized] || normalized;

  const found = PRIMARY_SOLUTIONS.find((s) => s.slug === canonicalSlug);
  if (found) return found;

  // Fallback generation for any niche in the 52-niche catalog
  const labels = NICHE_LABELS[canonicalSlug as NicheSlug] || {
    en: canonicalSlug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    vi: canonicalSlug.replace(/-/g, ' '),
  };

  return {
    slug: canonicalSlug,
    nameEn: labels.en,
    nameVi: labels.vi,
    category: 'Commercial Solutions',
    iconName: 'Sparkles',
    heroHeadlineEn: `Scale Your ${labels.en} Business With Automated Viral AI Video Production`,
    heroHeadlineVi: `Bứt Phá Tăng Trưởng Ngành ${labels.vi} Với Video AI Tự Động Triệu View`,
    heroSubheadlineEn: `Generate tailored hooks, high-converting scripts, and automated social videos for ${labels.en} in 60 seconds with Sophia AI Factory.`,
    heroSubheadlineVi: `Tự động tạo câu mở đầu thu hút, kịch bản chuyển đổi cao và video đa kênh cho lĩnh vực ${labels.vi} chỉ trong 60 giây cùng Sophia AI Factory.`,
    painPoints: [
      {
        titleEn: `High Video Production Costs for ${labels.en}`,
        titleVi: `Chi Phí Sản Xuất Video Ngành ${labels.vi} Quá Đắt`,
        descEn: `Traditional videography agencies charge upwards of $2,000/month with lengthy editing turnaround times.`,
        descVi: `Thuê đơn vị quay phim bên ngoài tốn hàng chục triệu mỗi tháng nhưng tốc độ bàn giao rất chậm.`,
      },
      {
        titleEn: `Struggling to Consistently Publish Social Content`,
        titleVi: `Không Đủ Thời Gian Để Đăng Video Đều Đặn`,
        descEn: `Social algorithms punish accounts that fail to upload daily short-form video content.`,
        descVi: `Thuật toán mạng xã hội ưu tiên tài khoản đăng video mỗi ngày, gây áp lực lớn cho đội ngũ marketing.`,
      },
      {
        titleEn: `Low Conversion From Generic Video Ads`,
        titleVi: `Tỉ Lệ Chuyển Đổi Kém Do Video Chung Chung`,
        descEn: `Generic marketing fails to touch real pain points; industry-tailored psychological hooks are essential.`,
        descVi: `Các mẫu quảng cáo rập khuôn không chạm đúng nỗi đau của khách hàng trong ngành ${labels.vi}.`,
      },
    ],
    samplePromptTitleEn: `${labels.en} Viral Short Video Formula`,
    samplePromptTitleVi: `Công Thức Video Ngắn Viral Cho ${labels.vi}`,
    samplePromptEn: `Create a 30-second high-energy problem-solution video for ${labels.en}. Hook: "If you are in ${labels.en} and struggling with customer acquisition in 2026, stop making this one costly mistake."`,
    samplePromptVi: `Tạo video 30 giây giải quyết vấn đề cho ngành ${labels.vi}. Hook: "Nếu bạn đang kinh doanh ${labels.vi} mà chưa có nhiều khách hàng trong năm 2026, dừng ngay lỗi sai tốn kém này lại."`,
    roiComparison: {
      traditionalAgencyCostMonthlyUsd: 2500,
      traditionalTurnaroundDays: 10,
      sophiaMonthlyUsd: 199,
      sophiaTurnaroundSeconds: 60,
      estimatedMonthlySavingsUsd: 2301,
      estimatedVideoOutputPerMonth: 60,
    },
    testimonial: {
      quoteEn: `Sophia transformed how we produce video content for our ${labels.en} business. The ROI has been remarkable.`,
      quoteVi: `Sophia đã thay đổi hoàn toàn cách chúng tôi làm video cho mảng ${labels.vi}. Hiệu quả mang lại vượt xa mong đợi.`,
      author: 'Nguyen Van Anh',
      roleEn: 'Business Owner',
      roleVi: 'Chủ Doanh Nghiệp',
      company: `${labels.en} Enterprise`,
      metrics: '3.4x lead generation increase',
    },
    faqs: [
      {
        questionEn: `How quickly can I generate videos for ${labels.en}?`,
        questionVi: `Mất bao lâu để tạo một video hoàn chỉnh cho ngành ${labels.vi}?`,
        answerEn: `With Sophia AI Factory, input your topic and receive a fully voiced, subtitled 1080p video in 60 seconds.`,
        answerVi: `Với Sophia AI Factory, bạn chỉ cần nhập chủ đề và nhận ngay video 1080p có phụ đề và lồng tiếng sau 60 giây.`,
      },
      {
        questionEn: `Can I claim the SOLO100 promo discount?`,
        questionVi: `Tôi có thể sử dụng mã giảm giá SOLO100 không?`,
        answerEn: `Yes, use promo code SOLO100 at checkout to save $100 immediately on the Starter plan.`,
        answerVi: `Chắc chắn rồi! Hãy nhập mã SOLO100 khi thanh toán để được giảm ngay 2.500.000 VNĐ ($100).`,
      },
    ],
    keywordsEn: [`${canonicalSlug} ai video`, `${canonicalSlug} video marketing`, `${canonicalSlug} reels generator`],
    keywordsVi: [`video ${labels.vi} ai`, `marketing ${labels.vi} tự động`, `tạo clip ${labels.vi} triệu view`],
  };
}
