/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--md-sys-color-primary)',
        'on-primary': 'var(--md-sys-color-on-primary)',
        'primary-hover': 'var(--md-sys-color-primary-hover)',
        'primary-container': 'var(--md-sys-color-primary-container)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        'primary-container-variant': 'var(--md-sys-color-primary-container-variant)',
        secondary: 'var(--md-sys-color-secondary)',
        'on-secondary': 'var(--md-sys-color-on-secondary)',
        'secondary-hover': 'var(--md-sys-color-secondary-hover)',
        'secondary-container': 'var(--md-sys-color-secondary-container)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        surface: 'var(--md-sys-color-surface)',
        'on-surface': 'var(--md-sys-color-on-surface)',
        'surface-variant': 'var(--md-sys-color-surface-variant)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'surface-container': 'var(--md-sys-color-surface-container)',
        'surface-container-low': 'var(--md-sys-color-surface-container-low)',
        'surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
        'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        outline: 'var(--md-sys-color-outline)',
        'inverse-primary': 'var(--md-sys-color-inverse-primary)',
        'on-inverse-primary': 'var(--md-sys-color-on-inverse-primary)',
        error: 'var(--md-sys-color-error)',
        'on-error': 'var(--md-sys-color-on-error)',
        'error-container': 'var(--md-sys-color-error-container)',
        'on-error-container': 'var(--md-sys-color-on-error-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        'on-tertiary': 'var(--md-sys-color-on-tertiary)',
        'tertiary-container': 'var(--md-sys-color-tertiary-container)',
        'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
        'inverse-surface': 'var(--md-sys-color-inverse-surface)',
        'inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        'surface-dark': 'var(--md-sys-color-surface-dark)',
        'surface-dark-high': 'var(--md-sys-color-surface-dark-high)',
        'surface-dark-dim': 'var(--md-sys-color-surface-dark-dim)',
        'on-surface-dark': 'var(--md-sys-color-on-surface-dark)',
        'on-surface-dark-variant': 'var(--md-sys-color-on-surface-dark-variant)',
      },
      borderRadius: {
        'md3-xs': 'var(--md-sys-shape-corner-extra-small)',
        'md3-sm': 'var(--md-sys-shape-corner-small)',
        'md3-md': 'var(--md-sys-shape-corner-medium)',
        'md3-lg': 'var(--md-sys-shape-corner-large)',
        'md3-xl': 'var(--md-sys-shape-corner-extra-large)',
        'md3-full': 'var(--md-sys-shape-corner-full)',
      },
      boxShadow: {
        'md3-1': 'var(--md-sys-elevation-level1)',
        'md3-2': 'var(--md-sys-elevation-level2)',
        'md3-3': 'var(--md-sys-elevation-level3)',
        'md3-4': 'var(--md-sys-elevation-level4)',
        'md3-5': 'var(--md-sys-elevation-level5)',
      },
    },
  },
  plugins: [],
}
